/* Generated by opensource COBOL 4J 2.1.0 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import jp.osscons.opensourcecobol.libcobj.sql.*;
import java.util.Optional;

public class CLAIMS implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return CLAIMS_(0, argStorages);
  }

  @Override
  public void cancel() {
    CLAIMS_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int CLAIMS_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	h_CLAIMS_FILE.close (0, null);
    	h_PAYMENTS_FILE.close (0, null);
    	h_REPORT_FILE.close (0, null);
    	h_SETTLE_FILE.close (0, null);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("CLAIMS");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("CLAIMS");

      b_RETURN_CODE.set((int)0);
      b_WS_EOF_CLAIMS.setByte(0, 'N');      b_WS_EOF_PAYMENTS.setByte(0, 'N');      b_WS_CLAIM_COUNT.fillBytes (48, 2);
      b_WS_APPROVED_COUNT.fillBytes (48, 2);
      b_WS_REJECTED_COUNT.fillBytes (48, 2);
      b_WS_PENDING_COUNT.fillBytes (48, 2);
      b_WS_PAID_COUNT.fillBytes (48, 2);
      b_WS_UNPAID_COUNT.fillBytes (48, 2);
      b_WS_TOTAL_CLAIMS.fillBytes (48, 6);
      b_WS_TOTAL_PAYMENTS.fillBytes (48, 6);
      b_WS_CLAIM_AMOUNT.fillBytes (48, 5);
      b_WS_PAY_MATCH_AMOUNT.fillBytes (48, 5);
      b_WS_PAY_MATCH_FOUND.setByte(0, 'N');      b_WS_SETTLEMENT_STATUS.fillBytes(' ', 13);
      b_WS_CR_CLAIM_ID.fillBytes(' ', 4);
      b_WS_CR_PATIENT_NAME.fillBytes(' ', 12);
      b_WS_CR_SERVICE_DATE.fillBytes(' ', 8);
      b_WS_CR_AMOUNT_STR.fillBytes(' ', 5);
      b_WS_CR_STATUS.setByte(' ');
      b_WS_CR_CATEGORY.fillBytes(' ', 8);
      b_WS_PR_PAY_ID.fillBytes(' ', 4);
      b_WS_PR_CLAIM_ID.fillBytes(' ', 4);
      b_WS_PR_PAY_DATE.fillBytes(' ', 8);
      b_WS_PR_AMOUNT_STR.fillBytes(' ', 5);
      b_WS_PR_METHOD.fillBytes(' ', 13);
      for (int i1 = 1; i1 <= 20; i1++)
      {
        b_WS_PT_CLAIM_ID__WS_PAY_ENTRY__WS_PAY_TABLE.getSubDataStorage(9 * (i1 - 1)).fillBytes(' ', 4);
        b_WS_PT_AMOUNT__WS_PAY_ENTRY__WS_PAY_TABLE.getSubDataStorage(9 * (i1 - 1)).fillBytes('0', 5);

      }
      b_WS_PAY_COUNT.fillBytes (48, 2);
      b_WS_PAY_IDX.fillBytes (48, 2);
      b_WS_HEADER.memcpy(str_0_CLAIM, 56);
      b_WS_HEADER.memset(56, 32, 24);      b_WS_SPACER.fillBytes (32, 80);

      h_CLAIMS_FILE = CobolFileFactory.makeCobolFileInstance(
      /* select_name = */ "CLAIMS-FILE",
      /* file_status = */ h_CLAIMS_FILE_status,
      /* assign = */ c_1,
      /* record = */ f_CLAIMS_FILE_record,
      /* record_size = */ null,
      /* record_min = */ 0,
      /* record_max = */ 60,
      /* nkeys = */ 0,
      /* keys = */ null,
      /* organization = */ (char)1,
      /* access_mode = */ (char)1,
      /* lock_mode = */ (char)2,
      /* open_mode = */ (char)0,
      /* flag_optional = */ false,
      /* last_open_mode = */ (char)0,
      /* special = */ (char)0,
      /* flag_nonexistent = */ false,
      /* flag_end_of_file = */ false,
      /* flag_begin_of_file = */ false,
      /* flag_first_read = */ (char)0,
      /* flag_read_done = */ false,
      /* flag_select_features = */ (char)0,
      /* flag_needs_nl = */ false,
      /* flag_needs_top = */ false,
      /* file_version = */ (char)0
      );
      h_PAYMENTS_FILE = CobolFileFactory.makeCobolFileInstance(
      /* select_name = */ "PAYMENTS-FILE",
      /* file_status = */ h_PAYMENTS_FILE_status,
      /* assign = */ c_2,
      /* record = */ f_PAYMENTS_FILE_record,
      /* record_size = */ null,
      /* record_min = */ 0,
      /* record_max = */ 60,
      /* nkeys = */ 0,
      /* keys = */ null,
      /* organization = */ (char)1,
      /* access_mode = */ (char)1,
      /* lock_mode = */ (char)2,
      /* open_mode = */ (char)0,
      /* flag_optional = */ false,
      /* last_open_mode = */ (char)0,
      /* special = */ (char)0,
      /* flag_nonexistent = */ false,
      /* flag_end_of_file = */ false,
      /* flag_begin_of_file = */ false,
      /* flag_first_read = */ (char)0,
      /* flag_read_done = */ false,
      /* flag_select_features = */ (char)0,
      /* flag_needs_nl = */ false,
      /* flag_needs_top = */ false,
      /* file_version = */ (char)0
      );
      h_REPORT_FILE = CobolFileFactory.makeCobolFileInstance(
      /* select_name = */ "REPORT-FILE",
      /* file_status = */ h_REPORT_FILE_status,
      /* assign = */ c_3,
      /* record = */ f_REPORT_FILE_record,
      /* record_size = */ null,
      /* record_min = */ 0,
      /* record_max = */ 80,
      /* nkeys = */ 0,
      /* keys = */ null,
      /* organization = */ (char)1,
      /* access_mode = */ (char)1,
      /* lock_mode = */ (char)2,
      /* open_mode = */ (char)0,
      /* flag_optional = */ false,
      /* last_open_mode = */ (char)0,
      /* special = */ (char)0,
      /* flag_nonexistent = */ false,
      /* flag_end_of_file = */ false,
      /* flag_begin_of_file = */ false,
      /* flag_first_read = */ (char)0,
      /* flag_read_done = */ false,
      /* flag_select_features = */ (char)0,
      /* flag_needs_nl = */ false,
      /* flag_needs_top = */ false,
      /* file_version = */ (char)0
      );
      h_SETTLE_FILE = CobolFileFactory.makeCobolFileInstance(
      /* select_name = */ "SETTLE-FILE",
      /* file_status = */ h_SETTLE_FILE_status,
      /* assign = */ c_4,
      /* record = */ f_SETTLE_FILE_record,
      /* record_size = */ null,
      /* record_min = */ 0,
      /* record_max = */ 80,
      /* nkeys = */ 0,
      /* keys = */ null,
      /* organization = */ (char)1,
      /* access_mode = */ (char)1,
      /* lock_mode = */ (char)2,
      /* open_mode = */ (char)0,
      /* flag_optional = */ false,
      /* last_open_mode = */ (char)0,
      /* special = */ (char)0,
      /* flag_nonexistent = */ false,
      /* flag_end_of_file = */ false,
      /* flag_begin_of_file = */ false,
      /* flag_first_read = */ (char)0,
      /* flag_read_done = */ false,
      /* flag_select_features = */ (char)0,
      /* flag_needs_nl = */ false,
      /* flag_needs_top = */ false,
      /* file_version = */ (char)0
      );

      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_CLAIMS);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_CLAIMS]);
      }
    },
    /* Entry CLAIMS */
    new CobolControl(l_CLAIMS, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN_LOGIC]);
      }
    },
    /* MAIN-LOGIC */
    new CobolControl(l_MAIN_SECTION__MAIN_LOGIC, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* CLAIMS_SYSERR.cob:73: OPEN */
        {
          CobolRuntimeException.code = 0;
          {
            h_CLAIMS_FILE.open (1, 0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* CLAIMS_SYSERR.cob:74: OPEN */
        {
          CobolRuntimeException.code = 0;
          {
            h_PAYMENTS_FILE.open (1, 0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* CLAIMS_SYSERR.cob:75: OPEN */
        {
          CobolRuntimeException.code = 0;
          {
            h_REPORT_FILE.open (2, 1, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* CLAIMS_SYSERR.cob:76: OPEN */
        {
          CobolRuntimeException.code = 0;
          {
            h_SETTLE_FILE.open (2, 1, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* CLAIMS_SYSERR.cob:78: PERFORM */
        /* PERFORM LOAD-PAYMENTS */
        CobolControl.perform(contList, l_MAIN_SECTION__LOAD_PAYMENTS).run();
        /* CLAIMS_SYSERR.cob:80: MOVE */
        {
          b_REPORT_REC.setBytes (b_WS_HEADER, 80);
        }
        /* CLAIMS_SYSERR.cob:81: WRITE */
        CobolRuntimeException.code = 0;
        {
          h_REPORT_FILE.write (f_REPORT_REC, 2162689, null);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }
        /* CLAIMS_SYSERR.cob:82: MOVE */
        {
          b_REPORT_REC.setBytes (b_WS_SPACER, 80);
        }
        /* CLAIMS_SYSERR.cob:83: WRITE */
        CobolRuntimeException.code = 0;
        {
          h_REPORT_FILE.write (f_REPORT_REC, 2162689, null);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }
        /* CLAIMS_SYSERR.cob:85: PERFORM */
        for (;;)
        {
          if (((long)(Byte.toUnsignedInt(b_WS_EOF_CLAIMS.getByte(0)) - (int)89) == 0L))
            break;
          /* PERFORM PROCESS-CLAIMS */
          CobolControl.perform(contList, l_MAIN_SECTION__PROCESS_CLAIMS).run();
        }
        /* CLAIMS_SYSERR.cob:88: DISPLAY */
        {
          CobolTerminal.display (0, 1, 2, c_5_TOTAL_CLAIMS, f_WS_CLAIM_COUNT);
        }
        /* CLAIMS_SYSERR.cob:89: DISPLAY */
        {
          CobolTerminal.display (0, 1, 2, c_6_APPROVED, f_WS_APPROVED_COUNT);
        }
        /* CLAIMS_SYSERR.cob:90: DISPLAY */
        {
          CobolTerminal.display (0, 1, 2, c_7_REJECTED, f_WS_REJECTED_COUNT);
        }
        /* CLAIMS_SYSERR.cob:91: DISPLAY */
        {
          CobolTerminal.display (0, 1, 2, c_8_PENDING, f_WS_PENDING_COUNT);
        }
        /* CLAIMS_SYSERR.cob:92: DISPLAY */
        {
          CobolTerminal.display (0, 1, 2, c_9_PAID, f_WS_PAID_COUNT);
        }
        /* CLAIMS_SYSERR.cob:93: DISPLAY */
        {
          CobolTerminal.display (0, 1, 2, c_10_UNPAID, f_WS_UNPAID_COUNT);
        }
        /* CLAIMS_SYSERR.cob:94: DISPLAY */
        {
          CobolTerminal.display (0, 1, 2, c_11_TOTAL_CLAIM_AMT, f_WS_TOTAL_CLAIMS);
        }
        /* CLAIMS_SYSERR.cob:95: DISPLAY */
        {
          CobolTerminal.display (0, 1, 2, c_12_TOTAL_PAY_AMT, f_WS_TOTAL_PAYMENTS);
        }
        /* CLAIMS_SYSERR.cob:97: CLOSE */
        {
          CobolRuntimeException.code = 0;
          {
            h_CLAIMS_FILE.close (0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* CLAIMS_SYSERR.cob:98: CLOSE */
        {
          CobolRuntimeException.code = 0;
          {
            h_PAYMENTS_FILE.close (0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* CLAIMS_SYSERR.cob:99: CLOSE */
        {
          CobolRuntimeException.code = 0;
          {
            h_REPORT_FILE.close (0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* CLAIMS_SYSERR.cob:100: CLOSE */
        {
          CobolRuntimeException.code = 0;
          {
            h_SETTLE_FILE.close (0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* CLAIMS_SYSERR.cob:102: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }

        return Optional.of(contList[l_MAIN_SECTION__LOAD_PAYMENTS]);
      }
    },
    /* LOAD-PAYMENTS */
    new CobolControl(l_MAIN_SECTION__LOAD_PAYMENTS, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* CLAIMS_SYSERR.cob:105: READ */
        CobolRuntimeException.code = 0;
        {
          h_PAYMENTS_FILE.read (0, null, 1);
        }
        if (CobolRuntimeException.code != 0)
        {
          if (CobolRuntimeException.code == 0x0501)
          {
            {
              /* CLAIMS_SYSERR.cob:107: MOVE */
              {
                b_WS_EOF_PAYMENTS.setByte(89);
              }
            }
          }
          else
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        else
        {
          {
            /* CLAIMS_SYSERR.cob:109: ADD */
            {
              f_WS_PAY_COUNT.add (c_13_1, 4);
            }
            /* CLAIMS_SYSERR.cob:110: UNSTRING */
            {
              CobolString.unstringInit (f_PAYMENT_REC, 0, 1);
              CobolString.unstringDelimited (c_14, 0);
              CobolString.unstringInto (f_WS_PR_PAY_ID, 0, 0);
              CobolString.unstringInto (f_WS_PR_CLAIM_ID, 0, 0);
              CobolString.unstringInto (f_WS_PR_PAY_DATE, 0, 0);
              CobolString.unstringInto (f_WS_PR_AMOUNT_STR, 0, 0);
              CobolString.unstringInto (f_WS_PR_METHOD, 0, 0);
              CobolString.unstringFinish ();
            }
            /* CLAIMS_SYSERR.cob:117: MOVE */
            {
              b_WS_PT_CLAIM_ID__WS_PAY_ENTRY__WS_PAY_TABLE.getSubDataStorage(9 * (b_WS_PAY_COUNT.getNumdisp(2) - 1)).setBytes (b_WS_PR_CLAIM_ID, 4);
            }
            /* CLAIMS_SYSERR.cob:119: MOVE */
            {
              CobolFieldFactory.makeCobolField(5, b_WS_PT_AMOUNT__WS_PAY_ENTRY__WS_PAY_TABLE.getSubDataStorage(9 * (b_WS_PAY_COUNT.getNumdisp(2) - 1)), a_4_NumericDisplay_Digits5_Scale0).moveFrom (f_WS_PR_AMOUNT_STR);
            }
          }
        }
        /* CLAIMS_SYSERR.cob:122: IF */
        {
          if (((long)(Byte.toUnsignedInt(b_WS_EOF_PAYMENTS.getByte(0)) - (int)89) != 0L))
            {
              /* CLAIMS_SYSERR.cob:123: GO TO */
              {
                if(true) return Optional.of(contList[l_MAIN_SECTION__LOAD_PAYMENTS]);
              }
            }
        }

        return Optional.of(contList[l_MAIN_SECTION__PROCESS_CLAIMS]);
      }
    },
    /* PROCESS-CLAIMS */
    new CobolControl(l_MAIN_SECTION__PROCESS_CLAIMS, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* CLAIMS_SYSERR.cob:127: READ */
        CobolRuntimeException.code = 0;
        {
          h_CLAIMS_FILE.read (0, null, 1);
        }
        if (CobolRuntimeException.code != 0)
        {
          if (CobolRuntimeException.code == 0x0501)
          {
            {
              /* CLAIMS_SYSERR.cob:129: MOVE */
              {
                b_WS_EOF_CLAIMS.setByte(89);
              }
            }
          }
          else
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        else
        {
          {
            /* CLAIMS_SYSERR.cob:131: ADD */
            {
              f_WS_CLAIM_COUNT.add (c_13_1, 4);
            }
            /* CLAIMS_SYSERR.cob:133: UNSTRING */
            {
              CobolString.unstringInit (f_CLAIM_REC, 0, 1);
              CobolString.unstringDelimited (c_14, 0);
              CobolString.unstringInto (f_WS_CR_CLAIM_ID, 0, 0);
              CobolString.unstringInto (f_WS_CR_PATIENT_NAME, 0, 0);
              CobolString.unstringInto (f_WS_CR_SERVICE_DATE, 0, 0);
              CobolString.unstringInto (f_WS_CR_AMOUNT_STR, 0, 0);
              CobolString.unstringInto (f_WS_CR_STATUS, 0, 0);
              CobolString.unstringInto (f_WS_CR_CATEGORY, 0, 0);
              CobolString.unstringFinish ();
            }
            /* CLAIMS_SYSERR.cob:142: MOVE */
            {
              f_WS_CLAIM_AMOUNT.moveFrom (f_WS_CR_AMOUNT_STR);
            }
            /* CLAIMS_SYSERR.cob:143: ADD */
            {
              f_WS_TOTAL_CLAIMS.add (f_WS_CLAIM_AMOUNT, 4);
            }
            /* CLAIMS_SYSERR.cob:145: MOVE */
            {
              b_WS_PAY_MATCH_FOUND.setByte(78);
            }
            /* CLAIMS_SYSERR.cob:146: MOVE */
            {
              b_WS_PAY_MATCH_AMOUNT.fillBytes (48, 5);
            }
            /* CLAIMS_SYSERR.cob:148: IF */
            {
              if (((long)(Byte.toUnsignedInt(b_WS_CR_STATUS.getByte(0)) - (int)82) == 0L))
                {
                  /* CLAIMS_SYSERR.cob:149: MOVE */
                  {
                    b_WS_SETTLEMENT_STATUS.setBytes (str_1_REJECTED, 13);
                  }
                  /* CLAIMS_SYSERR.cob:150: ADD */
                  {
                    f_WS_REJECTED_COUNT.add (c_13_1, 4);
                  }
                }
              else
                {
                  /* CLAIMS_SYSERR.cob:152: IF */
                  {
                    if (((long)(Byte.toUnsignedInt(b_WS_CR_STATUS.getByte(0)) - (int)80) == 0L))
                      {
                        /* CLAIMS_SYSERR.cob:153: MOVE */
                        {
                          b_WS_SETTLEMENT_STATUS.setBytes (str_2_PENDING, 13);
                        }
                        /* CLAIMS_SYSERR.cob:154: ADD */
                        {
                          f_WS_PENDING_COUNT.add (c_13_1, 4);
                        }
                      }
                    else
                      {
                        /* CLAIMS_SYSERR.cob:156: IF */
                        {
                          if (((long)b_WS_CLAIM_AMOUNT.cmpNumdisp (5, 500) <  0L))
                            {
                              /* CLAIMS_SYSERR.cob:157: MOVE */
                              {
                                b_WS_SETTLEMENT_STATUS.setBytes (str_3_REJECTED, 13);
                              }
                              /* CLAIMS_SYSERR.cob:159: ADD */
                              {
                                f_WS_REJECTED_COUNT.add (c_13_1, 4);
                              }
                            }
                          else
                            {
                              /* CLAIMS_SYSERR.cob:161: MOVE */
                              {
                                b_WS_SETTLEMENT_STATUS.setBytes (str_4_APPROVED, 13);
                              }
                              /* CLAIMS_SYSERR.cob:163: ADD */
                              {
                                f_WS_APPROVED_COUNT.add (c_13_1, 4);
                              }
                              /* CLAIMS_SYSERR.cob:164: PERFORM */
                              /* PERFORM FIND-PAYMENT */
                              CobolControl.perform(contList, l_MAIN_SECTION__FIND_PAYMENT).run();
                              /* CLAIMS_SYSERR.cob:165: IF */
                              {
                                if (((long)(Byte.toUnsignedInt(b_WS_PAY_MATCH_FOUND.getByte(0)) - (int)89) == 0L))
                                  {
                                    /* CLAIMS_SYSERR.cob:166: ADD */
                                    {
                                      f_WS_TOTAL_PAYMENTS.add (f_WS_PAY_MATCH_AMOUNT, 4);
                                    }
                                    /* CLAIMS_SYSERR.cob:168: IF */
                                    {
                                      if (((long)b_WS_PAY_MATCH_AMOUNT.memcmp (b_WS_CLAIM_AMOUNT, 5) == 0L))
                                        {
                                          /* CLAIMS_SYSERR.cob:170: MOVE */
                                          {
                                            b_WS_SETTLEMENT_STATUS.setBytes (str_5_PAID_IN_FULL, 13);
                                          }
                                          /* CLAIMS_SYSERR.cob:172: ADD */
                                          {
                                            f_WS_PAID_COUNT.add (c_13_1, 4);
                                          }
                                        }
                                      else
                                        {
                                          /* CLAIMS_SYSERR.cob:174: MOVE */
                                          {
                                            b_WS_SETTLEMENT_STATUS.setBytes (str_6_PARTIAL, 13);
                                          }
                                          /* CLAIMS_SYSERR.cob:176: ADD */
                                          {
                                            f_WS_PAID_COUNT.add (c_13_1, 4);
                                          }
                                        }
                                    }
                                  }
                                else
                                  {
                                    /* CLAIMS_SYSERR.cob:179: MOVE */
                                    {
                                      b_WS_SETTLEMENT_STATUS.setBytes (str_7_UNPAID, 13);
                                    }
                                    /* CLAIMS_SYSERR.cob:181: ADD */
                                    {
                                      f_WS_UNPAID_COUNT.add (c_13_1, 4);
                                    }
                                  }
                              }
                            }
                        }
                      }
                  }
                }
            }
            /* CLAIMS_SYSERR.cob:187: MOVE */
            {
              b_REPORT_REC.fillBytes (32, 80);
            }
            /* CLAIMS_SYSERR.cob:188: STRING */
            {
              CobolString.stringInit (f_REPORT_REC, 0);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (f_WS_CR_CLAIM_ID);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (c_15);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (f_WS_CR_PATIENT_NAME);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (c_15);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (f_WS_CR_SERVICE_DATE);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (c_15);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (f_WS_CR_AMOUNT_STR);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (c_15);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (f_WS_CR_STATUS);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (c_15);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (f_WS_CR_CATEGORY);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (c_15);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (f_WS_SETTLEMENT_STATUS);
              CobolString.stringFinish ();
            }
            /* CLAIMS_SYSERR.cob:203: WRITE */
            CobolRuntimeException.code = 0;
            {
              h_REPORT_FILE.write (f_REPORT_REC, 2162689, null);
            }
            if (CobolRuntimeException.code != 0)
            {
              /* PERFORM Default Error Handler */
              CobolControl.perform(contList, l_Default_Error_Handler).run();
            }
            /* CLAIMS_SYSERR.cob:205: MOVE */
            {
              b_SETTLE_REC.fillBytes (32, 80);
            }
            /* CLAIMS_SYSERR.cob:206: STRING */
            {
              CobolString.stringInit (f_SETTLE_REC, 0);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (f_WS_CR_CLAIM_ID);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (c_14);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (f_WS_CR_PATIENT_NAME);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (c_14);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (f_WS_CR_AMOUNT_STR);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (c_14);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (f_WS_CR_CATEGORY);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (c_14);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (f_WS_SETTLEMENT_STATUS);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (c_14);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (f_WS_PAY_MATCH_AMOUNT);
              CobolString.stringFinish ();
            }
            /* CLAIMS_SYSERR.cob:219: WRITE */
            CobolRuntimeException.code = 0;
            {
              h_SETTLE_FILE.write (f_SETTLE_REC, 2162689, null);
            }
            if (CobolRuntimeException.code != 0)
            {
              /* PERFORM Default Error Handler */
              CobolControl.perform(contList, l_Default_Error_Handler).run();
            }
            /* CLAIMS_SYSERR.cob:221: IF */
            {
              if (((long)f_WS_SETTLEMENT_STATUS.compareTo (c_16_REJECTED) == 0L))
                {
                  /* CLAIMS_SYSERR.cob:222: DISPLAY */
                  {
                    CobolTerminal.display (1, 1, 6, c_17_REJECT, f_WS_CR_CLAIM_ID, c_15, f_WS_CR_PATIENT_NAME, c_18, f_WS_CR_STATUS);
                  }
                }
            }
            /* CLAIMS_SYSERR.cob:230: IF */
            {
              if ((((long)b_WS_CLAIM_AMOUNT.cmpNumdisp (5, 500) <  0L) && ((long)(Byte.toUnsignedInt(b_WS_CR_STATUS.getByte(0)) - (int)65) == 0L)))
                {
                  /* CLAIMS_SYSERR.cob:232: DISPLAY */
                  {
                    CobolTerminal.display (1, 1, 6, c_19_LOW_AMOUNT, f_WS_CR_CLAIM_ID, c_15, f_WS_CR_PATIENT_NAME, c_20, f_WS_CR_AMOUNT_STR);
                  }
                }
            }
          }
        }

        return Optional.of(contList[l_MAIN_SECTION__FIND_PAYMENT]);
      }
    },
    /* FIND-PAYMENT */
    new CobolControl(l_MAIN_SECTION__FIND_PAYMENT, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* CLAIMS_SYSERR.cob:242: MOVE */
        {
          b_WS_PAY_IDX.setBytes (str_8_01, 2);
        }
        /* CLAIMS_SYSERR.cob:243: PERFORM */
        for (;;)
        {
          if ((((long)b_WS_PAY_IDX.memcmp (b_WS_PAY_COUNT, 2) >  0L) || ((long)(Byte.toUnsignedInt(b_WS_PAY_MATCH_FOUND.getByte(0)) - (int)89) == 0L)))
            break;
          /* PERFORM CHECK-PAYMENT */
          CobolControl.perform(contList, l_MAIN_SECTION__CHECK_PAYMENT).run();
        }

        return Optional.of(contList[l_MAIN_SECTION__CHECK_PAYMENT]);
      }
    },
    /* CHECK-PAYMENT */
    new CobolControl(l_MAIN_SECTION__CHECK_PAYMENT, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* CLAIMS_SYSERR.cob:248: IF */
        {
          if (((long)b_WS_PT_CLAIM_ID__WS_PAY_ENTRY__WS_PAY_TABLE.getSubDataStorage(9 * (b_WS_PAY_IDX.getNumdisp(2) - 1)).memcmp (b_WS_CR_CLAIM_ID, 4) == 0L))
            {
              /* CLAIMS_SYSERR.cob:249: MOVE */
              {
                b_WS_PAY_MATCH_FOUND.setByte(89);
              }
              /* CLAIMS_SYSERR.cob:250: MOVE */
              {
                b_WS_PAY_MATCH_AMOUNT.setBytes (b_WS_PT_AMOUNT__WS_PAY_ENTRY__WS_PAY_TABLE.getSubDataStorage(9 * (b_WS_PAY_IDX.getNumdisp(2) - 1)), 5);
              }
            }
        }
        /* CLAIMS_SYSERR.cob:253: ADD */
        {
          f_WS_PAY_IDX.add (c_13_1, 4);
        }


        return Optional.of(CobolControl.pure());
      }
    },
    /* Default Error Handler */
    new CobolControl(l_Default_Error_Handler, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        if ((CobolFile.errorFile.flag_select_features & CobolFile.COB_SELECT_FILE_STATUS) == 0) {
        	CobolFile.defaultErrorHandle ();
        	CobolStopRunException.stopRunAndThrow (1);
        }

        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new CLAIMS().CLAIMS_(0);
    CobolStopRunException.stopRun();
  }

  public CLAIMS()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : CLAIMS */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_CLAIMS_FILE_record = new CobolDataStorage(60);	/* CLAIMS-FILE_record */
    b_PAYMENTS_FILE_record = new CobolDataStorage(60);	/* PAYMENTS-FILE_record */
    b_REPORT_FILE_record = new CobolDataStorage(80);	/* REPORT-FILE_record */
    b_SETTLE_FILE_record = new CobolDataStorage(80);	/* SETTLE-FILE_record */
    b_WS_EOF_CLAIMS = new CobolDataStorage(1);	/* WS-EOF-CLAIMS */
    b_WS_EOF_PAYMENTS = new CobolDataStorage(1);	/* WS-EOF-PAYMENTS */
    b_WS_CLAIM_COUNT = new CobolDataStorage(2);	/* WS-CLAIM-COUNT */
    b_WS_APPROVED_COUNT = new CobolDataStorage(2);	/* WS-APPROVED-COUNT */
    b_WS_REJECTED_COUNT = new CobolDataStorage(2);	/* WS-REJECTED-COUNT */
    b_WS_PENDING_COUNT = new CobolDataStorage(2);	/* WS-PENDING-COUNT */
    b_WS_PAID_COUNT = new CobolDataStorage(2);	/* WS-PAID-COUNT */
    b_WS_UNPAID_COUNT = new CobolDataStorage(2);	/* WS-UNPAID-COUNT */
    b_WS_TOTAL_CLAIMS = new CobolDataStorage(6);	/* WS-TOTAL-CLAIMS */
    b_WS_TOTAL_PAYMENTS = new CobolDataStorage(6);	/* WS-TOTAL-PAYMENTS */
    b_WS_CLAIM_AMOUNT = new CobolDataStorage(5);	/* WS-CLAIM-AMOUNT */
    b_WS_PAY_MATCH_AMOUNT = new CobolDataStorage(5);	/* WS-PAY-MATCH-AMOUNT */
    b_WS_PAY_MATCH_FOUND = new CobolDataStorage(1);	/* WS-PAY-MATCH-FOUND */
    b_WS_SETTLEMENT_STATUS = new CobolDataStorage(13);	/* WS-SETTLEMENT-STATUS */
    b_WS_CR_CLAIM_ID = new CobolDataStorage(4);	/* WS-CR-CLAIM-ID */
    b_WS_CR_PATIENT_NAME = new CobolDataStorage(12);	/* WS-CR-PATIENT-NAME */
    b_WS_CR_SERVICE_DATE = new CobolDataStorage(8);	/* WS-CR-SERVICE-DATE */
    b_WS_CR_AMOUNT_STR = new CobolDataStorage(5);	/* WS-CR-AMOUNT-STR */
    b_WS_CR_STATUS = new CobolDataStorage(1);	/* WS-CR-STATUS */
    b_WS_CR_CATEGORY = new CobolDataStorage(8);	/* WS-CR-CATEGORY */
    b_WS_PR_PAY_ID = new CobolDataStorage(4);	/* WS-PR-PAY-ID */
    b_WS_PR_CLAIM_ID = new CobolDataStorage(4);	/* WS-PR-CLAIM-ID */
    b_WS_PR_PAY_DATE = new CobolDataStorage(8);	/* WS-PR-PAY-DATE */
    b_WS_PR_AMOUNT_STR = new CobolDataStorage(5);	/* WS-PR-AMOUNT-STR */
    b_WS_PR_METHOD = new CobolDataStorage(13);	/* WS-PR-METHOD */
    b_WS_PAY_TABLE = new CobolDataStorage(180);	/* WS-PAY-TABLE */
    b_WS_PAY_COUNT = new CobolDataStorage(2);	/* WS-PAY-COUNT */
    b_WS_PAY_IDX = new CobolDataStorage(2);	/* WS-PAY-IDX */
    b_WS_HEADER = new CobolDataStorage(80);	/* WS-HEADER */
    b_WS_SPACER = new CobolDataStorage(80);	/* WS-SPACER */
    b_CLAIM_REC = b_CLAIMS_FILE_record;
    b_PAYMENT_REC = b_PAYMENTS_FILE_record;
    b_REPORT_REC = b_REPORT_FILE_record;
    b_SETTLE_REC = b_SETTLE_FILE_record;
    b_WS_PT_AMOUNT__WS_PAY_ENTRY__WS_PAY_TABLE = b_WS_PAY_TABLE.getSubDataStorage(4);
    b_WS_PT_CLAIM_ID__WS_PAY_ENTRY__WS_PAY_TABLE = b_WS_PAY_TABLE;

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : CLAIMS */
    f_CLAIM_REC	= CobolFieldFactory.makeCobolField(60, b_CLAIM_REC, a_1_Alphanumeric);	/* CLAIM-REC */
    f_CLAIMS_FILE_record	= CobolFieldFactory.makeCobolField(60, b_CLAIMS_FILE_record, a_1_Alphanumeric);	/* CLAIMS-FILE_record */
    f_PAYMENT_REC	= CobolFieldFactory.makeCobolField(60, b_PAYMENT_REC, a_1_Alphanumeric);	/* PAYMENT-REC */
    f_PAYMENTS_FILE_record	= CobolFieldFactory.makeCobolField(60, b_PAYMENTS_FILE_record, a_1_Alphanumeric);	/* PAYMENTS-FILE_record */
    f_REPORT_REC	= CobolFieldFactory.makeCobolField(80, b_REPORT_REC, a_1_Alphanumeric);	/* REPORT-REC */
    f_REPORT_FILE_record	= CobolFieldFactory.makeCobolField(80, b_REPORT_FILE_record, a_1_Alphanumeric);	/* REPORT-FILE_record */
    f_SETTLE_REC	= CobolFieldFactory.makeCobolField(80, b_SETTLE_REC, a_1_Alphanumeric);	/* SETTLE-REC */
    f_SETTLE_FILE_record	= CobolFieldFactory.makeCobolField(80, b_SETTLE_FILE_record, a_1_Alphanumeric);	/* SETTLE-FILE_record */
    f_WS_CLAIM_COUNT	= CobolFieldFactory.makeCobolField(2, b_WS_CLAIM_COUNT, a_2_NumericDisplay_Digits2_Scale0);	/* WS-CLAIM-COUNT */
    f_WS_APPROVED_COUNT	= CobolFieldFactory.makeCobolField(2, b_WS_APPROVED_COUNT, a_2_NumericDisplay_Digits2_Scale0);	/* WS-APPROVED-COUNT */
    f_WS_REJECTED_COUNT	= CobolFieldFactory.makeCobolField(2, b_WS_REJECTED_COUNT, a_2_NumericDisplay_Digits2_Scale0);	/* WS-REJECTED-COUNT */
    f_WS_PENDING_COUNT	= CobolFieldFactory.makeCobolField(2, b_WS_PENDING_COUNT, a_2_NumericDisplay_Digits2_Scale0);	/* WS-PENDING-COUNT */
    f_WS_PAID_COUNT	= CobolFieldFactory.makeCobolField(2, b_WS_PAID_COUNT, a_2_NumericDisplay_Digits2_Scale0);	/* WS-PAID-COUNT */
    f_WS_UNPAID_COUNT	= CobolFieldFactory.makeCobolField(2, b_WS_UNPAID_COUNT, a_2_NumericDisplay_Digits2_Scale0);	/* WS-UNPAID-COUNT */
    f_WS_TOTAL_CLAIMS	= CobolFieldFactory.makeCobolField(6, b_WS_TOTAL_CLAIMS, a_3_NumericDisplay_Digits6_Scale0);	/* WS-TOTAL-CLAIMS */
    f_WS_TOTAL_PAYMENTS	= CobolFieldFactory.makeCobolField(6, b_WS_TOTAL_PAYMENTS, a_3_NumericDisplay_Digits6_Scale0);	/* WS-TOTAL-PAYMENTS */
    f_WS_CLAIM_AMOUNT	= CobolFieldFactory.makeCobolField(5, b_WS_CLAIM_AMOUNT, a_4_NumericDisplay_Digits5_Scale0);	/* WS-CLAIM-AMOUNT */
    f_WS_PAY_MATCH_AMOUNT	= CobolFieldFactory.makeCobolField(5, b_WS_PAY_MATCH_AMOUNT, a_4_NumericDisplay_Digits5_Scale0);	/* WS-PAY-MATCH-AMOUNT */
    f_WS_SETTLEMENT_STATUS	= CobolFieldFactory.makeCobolField(13, b_WS_SETTLEMENT_STATUS, a_1_Alphanumeric);	/* WS-SETTLEMENT-STATUS */
    f_WS_CR_CLAIM_ID	= CobolFieldFactory.makeCobolField(4, b_WS_CR_CLAIM_ID, a_1_Alphanumeric);	/* WS-CR-CLAIM-ID */
    f_WS_CR_PATIENT_NAME	= CobolFieldFactory.makeCobolField(12, b_WS_CR_PATIENT_NAME, a_1_Alphanumeric);	/* WS-CR-PATIENT-NAME */
    f_WS_CR_SERVICE_DATE	= CobolFieldFactory.makeCobolField(8, b_WS_CR_SERVICE_DATE, a_1_Alphanumeric);	/* WS-CR-SERVICE-DATE */
    f_WS_CR_AMOUNT_STR	= CobolFieldFactory.makeCobolField(5, b_WS_CR_AMOUNT_STR, a_1_Alphanumeric);	/* WS-CR-AMOUNT-STR */
    f_WS_CR_STATUS	= CobolFieldFactory.makeCobolField(1, b_WS_CR_STATUS, a_1_Alphanumeric);	/* WS-CR-STATUS */
    f_WS_CR_CATEGORY	= CobolFieldFactory.makeCobolField(8, b_WS_CR_CATEGORY, a_1_Alphanumeric);	/* WS-CR-CATEGORY */
    f_WS_PR_PAY_ID	= CobolFieldFactory.makeCobolField(4, b_WS_PR_PAY_ID, a_1_Alphanumeric);	/* WS-PR-PAY-ID */
    f_WS_PR_CLAIM_ID	= CobolFieldFactory.makeCobolField(4, b_WS_PR_CLAIM_ID, a_1_Alphanumeric);	/* WS-PR-CLAIM-ID */
    f_WS_PR_PAY_DATE	= CobolFieldFactory.makeCobolField(8, b_WS_PR_PAY_DATE, a_1_Alphanumeric);	/* WS-PR-PAY-DATE */
    f_WS_PR_AMOUNT_STR	= CobolFieldFactory.makeCobolField(5, b_WS_PR_AMOUNT_STR, a_1_Alphanumeric);	/* WS-PR-AMOUNT-STR */
    f_WS_PR_METHOD	= CobolFieldFactory.makeCobolField(13, b_WS_PR_METHOD, a_1_Alphanumeric);	/* WS-PR-METHOD */
    f_WS_PAY_COUNT	= CobolFieldFactory.makeCobolField(2, b_WS_PAY_COUNT, a_2_NumericDisplay_Digits2_Scale0);	/* WS-PAY-COUNT */
    f_WS_PAY_IDX	= CobolFieldFactory.makeCobolField(2, b_WS_PAY_IDX, a_2_NumericDisplay_Digits2_Scale0);	/* WS-PAY-IDX */

    /* End of fields */


    /* Constants */

    c_1	= CobolFieldFactory.makeCobolField(str_9, a_1_Alphanumeric);
    c_2	= CobolFieldFactory.makeCobolField(str_10, a_1_Alphanumeric);
    c_3	= CobolFieldFactory.makeCobolField(str_11, a_1_Alphanumeric);
    c_4	= CobolFieldFactory.makeCobolField(str_12, a_1_Alphanumeric);
    c_5_TOTAL_CLAIMS	= CobolFieldFactory.makeCobolField(str_13_TOTAL_CLAIMS, a_1_Alphanumeric);
    c_6_APPROVED	= CobolFieldFactory.makeCobolField(str_14_APPROVED, a_1_Alphanumeric);
    c_7_REJECTED	= CobolFieldFactory.makeCobolField(str_15_REJECTED, a_1_Alphanumeric);
    c_8_PENDING	= CobolFieldFactory.makeCobolField(str_16_PENDING, a_1_Alphanumeric);
    c_9_PAID	= CobolFieldFactory.makeCobolField(str_17_PAID, a_1_Alphanumeric);
    c_10_UNPAID	= CobolFieldFactory.makeCobolField(str_18_UNPAID, a_1_Alphanumeric);
    c_11_TOTAL_CLAIM_AMT	= CobolFieldFactory.makeCobolField(str_19_TOTAL_CLAIM_AMT, a_1_Alphanumeric);
    c_12_TOTAL_PAY_AMT	= CobolFieldFactory.makeCobolField(str_20_TOTAL_PAY_AMT, a_1_Alphanumeric);
    c_13_1	= CobolFieldFactory.makeCobolField(1, "1", a_5_NumericDisplay_Digits1_Scale0);
    c_14	= CobolFieldFactory.makeCobolField(str_21, a_1_Alphanumeric);
    c_15	= CobolFieldFactory.makeCobolField(str_22, a_1_Alphanumeric);
    c_16_REJECTED	= CobolFieldFactory.makeCobolField(str_23_REJECTED, a_1_Alphanumeric);
    c_17_REJECT	= CobolFieldFactory.makeCobolField(str_24_REJECT, a_1_Alphanumeric);
    c_18	= CobolFieldFactory.makeCobolField(str_25, a_1_Alphanumeric);
    c_19_LOW_AMOUNT	= CobolFieldFactory.makeCobolField(str_26_LOW_AMOUNT, a_1_Alphanumeric);
    c_20	= CobolFieldFactory.makeCobolField(str_27, a_1_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_NumericDisplay_Digits2_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 2,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits6_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 6,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_4_NumericDisplay_Digits5_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 5,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_5_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : CLAIMS */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_CLAIMS_FILE_record;	/* CLAIMS-FILE_record */
  private CobolDataStorage b_PAYMENTS_FILE_record;	/* PAYMENTS-FILE_record */
  private CobolDataStorage b_REPORT_FILE_record;	/* REPORT-FILE_record */
  private CobolDataStorage b_SETTLE_FILE_record;	/* SETTLE-FILE_record */
  private CobolDataStorage b_WS_EOF_CLAIMS;	/* WS-EOF-CLAIMS */
  private CobolDataStorage b_WS_EOF_PAYMENTS;	/* WS-EOF-PAYMENTS */
  private CobolDataStorage b_WS_CLAIM_COUNT;	/* WS-CLAIM-COUNT */
  private CobolDataStorage b_WS_APPROVED_COUNT;	/* WS-APPROVED-COUNT */
  private CobolDataStorage b_WS_REJECTED_COUNT;	/* WS-REJECTED-COUNT */
  private CobolDataStorage b_WS_PENDING_COUNT;	/* WS-PENDING-COUNT */
  private CobolDataStorage b_WS_PAID_COUNT;	/* WS-PAID-COUNT */
  private CobolDataStorage b_WS_UNPAID_COUNT;	/* WS-UNPAID-COUNT */
  private CobolDataStorage b_WS_TOTAL_CLAIMS;	/* WS-TOTAL-CLAIMS */
  private CobolDataStorage b_WS_TOTAL_PAYMENTS;	/* WS-TOTAL-PAYMENTS */
  private CobolDataStorage b_WS_CLAIM_AMOUNT;	/* WS-CLAIM-AMOUNT */
  private CobolDataStorage b_WS_PAY_MATCH_AMOUNT;	/* WS-PAY-MATCH-AMOUNT */
  private CobolDataStorage b_WS_PAY_MATCH_FOUND;	/* WS-PAY-MATCH-FOUND */
  private CobolDataStorage b_WS_SETTLEMENT_STATUS;	/* WS-SETTLEMENT-STATUS */
  private CobolDataStorage b_WS_CR_CLAIM_ID;	/* WS-CR-CLAIM-ID */
  private CobolDataStorage b_WS_CR_PATIENT_NAME;	/* WS-CR-PATIENT-NAME */
  private CobolDataStorage b_WS_CR_SERVICE_DATE;	/* WS-CR-SERVICE-DATE */
  private CobolDataStorage b_WS_CR_AMOUNT_STR;	/* WS-CR-AMOUNT-STR */
  private CobolDataStorage b_WS_CR_STATUS;	/* WS-CR-STATUS */
  private CobolDataStorage b_WS_CR_CATEGORY;	/* WS-CR-CATEGORY */
  private CobolDataStorage b_WS_PR_PAY_ID;	/* WS-PR-PAY-ID */
  private CobolDataStorage b_WS_PR_CLAIM_ID;	/* WS-PR-CLAIM-ID */
  private CobolDataStorage b_WS_PR_PAY_DATE;	/* WS-PR-PAY-DATE */
  private CobolDataStorage b_WS_PR_AMOUNT_STR;	/* WS-PR-AMOUNT-STR */
  private CobolDataStorage b_WS_PR_METHOD;	/* WS-PR-METHOD */
  private CobolDataStorage b_WS_PAY_TABLE;	/* WS-PAY-TABLE */
  private CobolDataStorage b_WS_PAY_COUNT;	/* WS-PAY-COUNT */
  private CobolDataStorage b_WS_PAY_IDX;	/* WS-PAY-IDX */
  private CobolDataStorage b_WS_HEADER;	/* WS-HEADER */
  private CobolDataStorage b_WS_SPACER;	/* WS-SPACER */
  private CobolDataStorage b_CLAIM_REC;
  private CobolDataStorage b_PAYMENT_REC;
  private CobolDataStorage b_REPORT_REC;
  private CobolDataStorage b_SETTLE_REC;
  private CobolDataStorage b_WS_PT_AMOUNT__WS_PAY_ENTRY__WS_PAY_TABLE;
  private CobolDataStorage b_WS_PT_CLAIM_ID__WS_PAY_ENTRY__WS_PAY_TABLE;

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : CLAIMS */
  private AbstractCobolField f_CLAIM_REC;	/* CLAIM-REC */
  private AbstractCobolField f_CLAIMS_FILE_record;	/* CLAIMS-FILE_record */
  private AbstractCobolField f_PAYMENT_REC;	/* PAYMENT-REC */
  private AbstractCobolField f_PAYMENTS_FILE_record;	/* PAYMENTS-FILE_record */
  private AbstractCobolField f_REPORT_REC;	/* REPORT-REC */
  private AbstractCobolField f_REPORT_FILE_record;	/* REPORT-FILE_record */
  private AbstractCobolField f_SETTLE_REC;	/* SETTLE-REC */
  private AbstractCobolField f_SETTLE_FILE_record;	/* SETTLE-FILE_record */
  private AbstractCobolField f_WS_CLAIM_COUNT;	/* WS-CLAIM-COUNT */
  private AbstractCobolField f_WS_APPROVED_COUNT;	/* WS-APPROVED-COUNT */
  private AbstractCobolField f_WS_REJECTED_COUNT;	/* WS-REJECTED-COUNT */
  private AbstractCobolField f_WS_PENDING_COUNT;	/* WS-PENDING-COUNT */
  private AbstractCobolField f_WS_PAID_COUNT;	/* WS-PAID-COUNT */
  private AbstractCobolField f_WS_UNPAID_COUNT;	/* WS-UNPAID-COUNT */
  private AbstractCobolField f_WS_TOTAL_CLAIMS;	/* WS-TOTAL-CLAIMS */
  private AbstractCobolField f_WS_TOTAL_PAYMENTS;	/* WS-TOTAL-PAYMENTS */
  private AbstractCobolField f_WS_CLAIM_AMOUNT;	/* WS-CLAIM-AMOUNT */
  private AbstractCobolField f_WS_PAY_MATCH_AMOUNT;	/* WS-PAY-MATCH-AMOUNT */
  private AbstractCobolField f_WS_SETTLEMENT_STATUS;	/* WS-SETTLEMENT-STATUS */
  private AbstractCobolField f_WS_CR_CLAIM_ID;	/* WS-CR-CLAIM-ID */
  private AbstractCobolField f_WS_CR_PATIENT_NAME;	/* WS-CR-PATIENT-NAME */
  private AbstractCobolField f_WS_CR_SERVICE_DATE;	/* WS-CR-SERVICE-DATE */
  private AbstractCobolField f_WS_CR_AMOUNT_STR;	/* WS-CR-AMOUNT-STR */
  private AbstractCobolField f_WS_CR_STATUS;	/* WS-CR-STATUS */
  private AbstractCobolField f_WS_CR_CATEGORY;	/* WS-CR-CATEGORY */
  private AbstractCobolField f_WS_PR_PAY_ID;	/* WS-PR-PAY-ID */
  private AbstractCobolField f_WS_PR_CLAIM_ID;	/* WS-PR-CLAIM-ID */
  private AbstractCobolField f_WS_PR_PAY_DATE;	/* WS-PR-PAY-DATE */
  private AbstractCobolField f_WS_PR_AMOUNT_STR;	/* WS-PR-AMOUNT-STR */
  private AbstractCobolField f_WS_PR_METHOD;	/* WS-PR-METHOD */
  private AbstractCobolField f_WS_PAY_COUNT;	/* WS-PAY-COUNT */
  private AbstractCobolField f_WS_PAY_IDX;	/* WS-PAY-IDX */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_20;
  private AbstractCobolField c_19_LOW_AMOUNT;
  private AbstractCobolField c_18;
  private AbstractCobolField c_17_REJECT;
  private AbstractCobolField c_16_REJECTED;
  private AbstractCobolField c_15;
  private AbstractCobolField c_14;
  private AbstractCobolField c_13_1;
  private AbstractCobolField c_12_TOTAL_PAY_AMT;
  private AbstractCobolField c_11_TOTAL_CLAIM_AMT;
  private AbstractCobolField c_10_UNPAID;
  private AbstractCobolField c_9_PAID;
  private AbstractCobolField c_8_PENDING;
  private AbstractCobolField c_7_REJECTED;
  private AbstractCobolField c_6_APPROVED;
  private AbstractCobolField c_5_TOTAL_CLAIMS;
  private AbstractCobolField c_4;
  private AbstractCobolField c_3;
  private AbstractCobolField c_2;
  private AbstractCobolField c_1;

  /* Attributes */

  private CobolFieldAttribute a_5_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_4_NumericDisplay_Digits5_Scale0;
  private CobolFieldAttribute a_3_NumericDisplay_Digits6_Scale0;
  private CobolFieldAttribute a_2_NumericDisplay_Digits2_Scale0;
  private CobolFieldAttribute a_1_Alphanumeric;



  /* String literals */
  public static final byte[] str_27 = CobolUtil.stringToBytes(" amt=");
  public static final byte[] str_26_LOW_AMOUNT = CobolUtil.stringToBytes("LOW_AMOUNT:");
  public static final byte[] str_25 = CobolUtil.stringToBytes(" reason=");
  public static final byte[] str_24_REJECT = CobolUtil.stringToBytes("REJECT:");
  public static final byte[] str_23_REJECTED = CobolUtil.stringToBytes("REJECTED");
  public static final byte[] str_22 = CobolUtil.stringToBytes(" ");
  public static final byte[] str_21 = CobolUtil.stringToBytes("|");
  public static final byte[] str_20_TOTAL_PAY_AMT = CobolUtil.stringToBytes("TOTAL_PAY_AMT=");
  public static final byte[] str_19_TOTAL_CLAIM_AMT = CobolUtil.stringToBytes("TOTAL_CLAIM_AMT=");
  public static final byte[] str_18_UNPAID = CobolUtil.stringToBytes("UNPAID=");
  public static final byte[] str_17_PAID = CobolUtil.stringToBytes("PAID=");
  public static final byte[] str_16_PENDING = CobolUtil.stringToBytes("PENDING=");
  public static final byte[] str_15_REJECTED = CobolUtil.stringToBytes("REJECTED=");
  public static final byte[] str_14_APPROVED = CobolUtil.stringToBytes("APPROVED=");
  public static final byte[] str_13_TOTAL_CLAIMS = CobolUtil.stringToBytes("TOTAL_CLAIMS=");
  public static final byte[] str_12 = CobolUtil.stringToBytes("/workspace/output/settlement.dat");
  public static final byte[] str_11 = CobolUtil.stringToBytes("/workspace/output/report.txt");
  public static final byte[] str_10 = CobolUtil.stringToBytes("/workspace/input/payments.dat");
  public static final byte[] str_9 = CobolUtil.stringToBytes("/workspace/input/claims.dat");
  public static final byte[] str_8_01 = CobolUtil.stringToBytes("01");
  public static final byte[] str_7_UNPAID = CobolUtil.stringToBytes("UNPAID       ");
  public static final byte[] str_6_PARTIAL = CobolUtil.stringToBytes("PARTIAL      ");
  public static final byte[] str_5_PAID_IN_FULL = CobolUtil.stringToBytes("PAID_IN_FULL ");
  public static final byte[] str_4_APPROVED = CobolUtil.stringToBytes("APPROVED     ");
  public static final byte[] str_3_REJECTED = CobolUtil.stringToBytes("REJECTED     ");
  public static final byte[] str_2_PENDING = CobolUtil.stringToBytes("PENDING      ");
  public static final byte[] str_1_REJECTED = CobolUtil.stringToBytes("REJECTED     ");
  public static final byte[] str_0_CLAIM = CobolUtil.stringToBytes("CLAIM   PATIENT      DATE     AMT ST CAT      SETTLEMENT");
  /* File CLAIMS-FILE */
  private CobolFile		h_CLAIMS_FILE = null;
  private byte[]	h_CLAIMS_FILE_status = new byte[4];
  /* File PAYMENTS-FILE */
  private CobolFile		h_PAYMENTS_FILE = null;
  private byte[]	h_PAYMENTS_FILE_status = new byte[4];
  /* File REPORT-FILE */
  private CobolFile		h_REPORT_FILE = null;
  private byte[]	h_REPORT_FILE_status = new byte[4];
  /* File SETTLE-FILE */
  private CobolFile		h_SETTLE_FILE = null;
  private byte[]	h_SETTLE_FILE_status = new byte[4];

  /* Sections and Labels */
  private final static int l_CLAIMS = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__MAIN_LOGIC = 3;
  private final static int l_MAIN_SECTION__LOAD_PAYMENTS = 4;
  private final static int l_MAIN_SECTION__PROCESS_CLAIMS = 5;
  private final static int l_MAIN_SECTION__FIND_PAYMENT = 6;
  private final static int l_MAIN_SECTION__CHECK_PAYMENT = 7;
  private final static int l_Default_Error_Handler = 8;

}
