"""Java code generator from Java Application IR.

Generates native Java source code from a JavaApplication IR.
The generated Java:
- Uses only standard Java libraries (java.io, java.util)
- Reads actual workload input files
- Produces the same output artifacts as the source program
- Has no COBOL runtime dependency
- Is a genuine standalone Java application

Generation is mode-driven: JavaProgram.generation_mode selects the strategy:
1. "decision" — status codes, thresholds, lookups, record formats
2. "file_io" — UNSTRING parsing, input record processing
3. "minimal" — generic generation for simple programs
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from engine.transformation.java_ir import (
    JavaApplication,
    JavaClass,
    JavaField,
    JavaFileResource,
    JavaMatchOutcome,
    JavaProgram,
    JavaStatusCodeMapping,
    JavaSummaryField,
    JavaThresholdRule,
)


@dataclass
class GeneratedFile:
    """A generated Java source file."""
    filename: str
    source_code: str
    class_name: str


class JavaGenerator:
    """Generates Java source from Java Application IR.

    Primary entry point: generate_from_java(application: JavaApplication)
    Backward-compatible: generate(program: CobolProgram) via mapping adapter.
    """

    def generate_from_java(self, application: JavaApplication) -> list[GeneratedFile]:
        """Generate Java source from JavaApplication IR.

        This is the primary entry point. The generator knows nothing about COBOL.
        For multi-program applications, generates:
        - One Java file per program
        - A service registry class for cross-program references
        """
        files: list[GeneratedFile] = []

        # Generate one file per program
        for program in application.programs:
            class_name = self._to_java_class_name(program.program_id)
            mode = program.generation_mode or "minimal"

            if mode == "decision":
                source = self._generate_decision_java_from_ir(program, class_name)
            elif mode == "file_io":
                source = self._generate_file_io_java_from_ir(program, class_name)
            else:
                source = self._generate_minimal_java_from_ir(program, class_name)

            files.append(GeneratedFile(
                filename=f"{class_name}.java",
                source_code=source,
                class_name=class_name,
            ))

        # Generate service registry for multi-program applications
        if len(application.programs) > 1:
            registry_source = self._generate_service_registry(application)
            files.append(GeneratedFile(
                filename="ServiceRegistry.java",
                source_code=registry_source,
                class_name="ServiceRegistry",
            ))

        return files

    def _generate_service_registry(self, application: JavaApplication) -> str:
        """Generate a service registry class for cross-program references.

        Creates a simple registry that allows programs to call each other.
        """
        lines = [
            "import java.util.HashMap;",
            "import java.util.Map;",
            "",
            "/**",
            f" * Service registry for application: {application.application_id}",
            " * Auto-generated by COBOL-to-Java transformer.",
            " */",
            "public class ServiceRegistry {",
            "",
            "    private static final ServiceRegistry INSTANCE = new ServiceRegistry();",
            "    private final Map<String, Object> services = new HashMap<>();",
            "",
            "    private ServiceRegistry() {}",
            "",
            "    public static ServiceRegistry getInstance() {",
            "        return INSTANCE;",
            "    }",
            "",
            "    public <T> void register(String name, T service) {",
            "        services.put(name, service);",
            "    }",
            "",
            "    @SuppressWarnings(\"unchecked\")",
            "    public <T> T get(String name) {",
            "        return (T) services.get(name);",
            "    }",
            "",
        ]

        # Add method stubs for each program's entry point
        for program in application.programs:
            class_name = self._to_java_class_name(program.program_id)
            lines.extend([
                f"    /** Call {class_name}. */",
                f"    public void call{class_name}() {{",
                f"        {class_name} program = get(\"{class_name}\");",
                f"        if (program != null) {{",
                f"            // program execution placeholder",
                f"        }}",
                f"    }}",
                "",
            ])

        lines.append("}")
        return "\n".join(lines)

    def generate(self, program: CobolProgram) -> list[GeneratedFile]:
        """Backward-compatible entry point: CobolProgram → Java source.

        Uses the mapping layer to convert CobolProgram → JavaApplication,
        then delegates to generate_from_java.
        """
        from engine.transformation.cobol_to_java_mapping import (
            map_cobol_program_to_java,
        )
        from engine.transformation.java_ir import JavaApplication

        java_program = map_cobol_program_to_java(program)
        application = JavaApplication(
            application_id=program.program_id,
            programs=(java_program,),
        )
        return self.generate_from_java(application)

    def _to_java_class_name(self, cobol_name: str) -> str:
        return cobol_name.replace("-", "_").replace(" ", "_").title()

    # ================================================================
    # IR-DRIVEN GENERATION METHODS (no COBOL knowledge)
    # ================================================================

    def _generate_decision_java_from_ir(self, program: JavaProgram, class_name: str) -> str:
        """Generate Java with IR-derived decision logic from JavaProgram.

        All values come from JavaProgram metadata — no COBOL IR access.
        """
        if not program.status_codes:
            return self._generate_minimal_java_from_ir(program, class_name)

        # Get file resources by access mode
        input_files = [r for r in program.file_resources
                       if r.access_mode.value in ("READ", "READ_WRITE")]
        output_files = [r for r in program.file_resources
                        if r.access_mode.value in ("WRITE", "READ_WRITE")]

        if len(input_files) < 2 or len(output_files) < 2:
            raise ValueError(
                "MISSING_REQUIRED_SEMANTIC: Decision mode requires "
                "2 input files and 2 output files."
            )

        input1_path = input_files[0].path
        input2_path = input_files[1].path
        output1_path = output_files[0].path
        output2_path = output_files[1].path

        input1_filename = input1_path.rsplit("/", 1)[1] if "/" in input1_path else None
        input2_filename = input2_path.rsplit("/", 1)[1] if "/" in input2_path else None
        output1_filename = output1_path.rsplit("/", 1)[1] if "/" in output1_path else None
        output2_filename = output2_path.rsplit("/", 1)[1] if "/" in output2_path else None

        if not all([input1_filename, input2_filename, output1_filename, output2_filename]):
            raise ValueError(
                "MISSING_REQUIRED_SEMANTIC: File path must contain a filename."
            )

        # Threshold from IR
        threshold = self._get_threshold_from_ir(program.threshold_rules)

        # Report header from IR
        report_config = program.report_config
        if not report_config or not report_config.header:
            raise ValueError(
                "MISSING_REQUIRED_SEMANTIC: No report header found."
            )
        report_header = report_config.header

        # Summary fields from IR
        if not program.summary_fields:
            raise ValueError(
                "MISSING_REQUIRED_SEMANTIC: No summary fields found."
            )

        # Get class fields for variable declarations
        java_class = program.java_class
        if not java_class:
            raise ValueError(
                "MISSING_REQUIRED_SEMANTIC: No Java class in program."
            )

        # Build field mappings from class fields
        field_map = {f.name: f for f in java_class.fields}

        # Status checks
        status_java = self._build_status_checks_java_from_ir(
            program.status_codes, program.match_outcomes,
            program.summary_fields, field_map, program.input_record_fields,
        )

        # Summary output
        summary_java = self._build_summary_java_from_ir(
            program.summary_fields, field_map,
        )

        # Variable declarations
        var_decls = self._generate_var_declarations_from_ir(
            program.status_codes, program.match_outcomes,
            program.summary_fields,
        )

        # Counter increments
        counter_increments = self._generate_counter_increments_from_ir(
            program.summary_fields,
        )

        # Field assignments from input record fields (positional)
        field_assignments = self._generate_field_assignments_from_ir(
            program, java_class,
        )

        # Status variable names (positional from input record fields)
        input_fields = program.input_record_fields or tuple(f.name for f in java_class.fields)
        id_var = input_fields[0] if len(input_fields) > 0 else "field_0"
        status_var = input_fields[1] if len(input_fields) > 1 else "field_1"
        amt_str_var = input_fields[-1] if len(input_fields) > 0 else "field_last"

        # Report write
        report_write = self._build_record_write_java_from_ir(
            "rpt", report_config.report_format_fields, field_map,
        )
        output_write = self._build_record_write_java_from_ir(
            "out", report_config.output_format_fields, field_map,
        )

        # Stderr diagnostics
        stderr_java = self._build_stderr_java_from_ir(
            program.status_codes, id_var, status_var, amt_str_var,
        )

        # Class-level field declarations
        field_decls = self._gen_field_declarations_from_ir(java_class)

        return f'''import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class {class_name} {{
    static final int THRESHOLD = {threshold};

{field_decls}

    public static void main(String[] args) throws Exception {{
        String inputDir = args.length > 0 ? args[0] : "{input1_path.rsplit('/', 1)[0]}";
        String outputDir = args.length > 1 ? args[1] : "{output1_path.rsplit('/', 1)[0]}";

{var_decls}

        List<String[]> input1 = readInput(inputDir + "/{input1_filename}");
        List<String[]> input2 = readInput(inputDir + "/{input2_filename}");

        Map<String, Integer> lookupMap = new LinkedHashMap<>();
        for (String[] r : input2) {{
            String key = r[1].trim();
            int value = Integer.parseInt(r[3].trim());
            lookupMap.put(key, value);
        }}

        PrintWriter rpt = new PrintWriter(new FileWriter(outputDir + "/{output1_filename}"));
        PrintWriter out = new PrintWriter(new FileWriter(outputDir + "/{output2_filename}"));

        rpt.println("{report_header}");
        rpt.println();

        for (String[] rec : input1) {{
{counter_increments}
{field_assignments}

            int {amt_str_var}_num = Integer.parseInt({amt_str_var}.trim());

            String result;
            int lookupMatch = 0;

{status_java}

{report_write}

{output_write}

{stderr_java}
        }}

{summary_java}

        rpt.close();
        out.close();
    }}

    static List<String[]> readInput(String path) throws Exception {{
        List<String[]> rows = new ArrayList<>();
        BufferedReader br = new BufferedReader(new FileReader(path));
        String line;
        while ((line = br.readLine()) != null) {{
            if (!line.trim().isEmpty()) {{
                rows.add(line.split("\\\\|", -1));
            }}
        }}
        br.close();
        return rows;
    }}

    static String padRight(String s, int n) {{
        if (s == null) {{
            s = "";
        }}
        if (s.length() >= n) {{
            return s.substring(0, n);
        }}
        StringBuilder sb = new StringBuilder(s);
        while (sb.length() < n) {{
            sb.append(' ');
        }}
        return sb.toString();
    }}
}}
'''

    def _generate_file_io_java_from_ir(self, program: JavaProgram, class_name: str) -> str:
        """Generate Java for file I/O programs from JavaProgram IR."""
        java_class = program.java_class
        if not java_class:
            raise ValueError("MISSING_REQUIRED_SEMANTIC: No Java class in program.")

        input_files = [r for r in program.file_resources
                       if r.access_mode.value in ("READ", "READ_WRITE")]
        if not input_files:
            raise ValueError("MISSING_REQUIRED_SEMANTIC: No input files found.")

        input_path = input_files[0].path
        input_dir = input_path.rsplit("/", 1)[0] if "/" in input_path else "."
        input_filename = input_path.rsplit("/", 1)[1] if "/" in input_path else None

        if not input_filename:
            raise ValueError("MISSING_REQUIRED_SEMANTIC: Input file path must contain a filename.")

        # Variable declarations from class fields
        declarations = self._gen_field_declarations_from_ir(java_class)

        # Parsing code from input file record
        parsing = self._gen_parsing_java_from_ir(input_files[0], java_class)

        # Main method body — from JavaProgram.java_class.methods (excluding main)
        main_body = ""
        loop_body = ""

        # Find the main method and extract its body
        for method in java_class.methods:
            if method.name == "main":
                # Split into loop and non-loop parts
                for stmt in method.body_statements:
                    # Simple heuristic: comments become loop body
                    stmt_str = str(type(stmt).__name__)
                    if hasattr(stmt, 'text') and stmt.text:
                        loop_body += f"            // {stmt.text}\n"
                    elif hasattr(stmt, 'expression'):
                        main_body += f"        {self._stmt_to_string(stmt)}\n"

        return f'''import java.io.BufferedReader;
import java.io.FileReader;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;

public class {class_name} {{

{declarations}

    public static void main(String[] args) throws Exception {{
        String inputDir = args.length > 0 ? args[0] : "{input_dir}";
        PrintStream out = System.out;

        List<String[]> records = new ArrayList<>();
        BufferedReader br = new BufferedReader(new FileReader(inputDir + "/{input_filename}"));
        String line;
        while ((line = br.readLine()) != null) {{
            if (!line.trim().isEmpty()) {{
                records.add(line.split("\\\\|", -1));
            }}
        }}
        br.close();

        for (String[] rec : records) {{
{parsing}

{loop_body}
        }}

{main_body}
    }}
}}
'''

    def _generate_minimal_java_from_ir(self, program: JavaProgram, class_name: str) -> str:
        """Generate Java for minimal programs from JavaProgram IR."""
        java_class = program.java_class
        if not java_class:
            raise ValueError("MISSING_REQUIRED_SEMANTIC: No Java class in program.")

        declarations = self._gen_field_declarations_from_ir(java_class)

        # Collect all method bodies (all non-main methods) and main body
        all_methods_src: list[str] = []
        main_body = ""
        uses_file_write = False
        uses_cobol_file_io_stmt = False

        for method in java_class.methods:
            method_stmts: list[str] = []
            for stmt in method.body_statements:
                stmt_str = self._stmt_to_string(stmt)
                if stmt_str:
                    method_stmts.append(stmt_str)
                    if "_FileWriteHelper" in stmt_str:
                        uses_file_write = True
                    if "CobolFileIo." in stmt_str:
                        uses_cobol_file_io_stmt = True

            if method.name == "main":
                main_body = "".join(f"        {s}\n" for s in method_stmts)
            else:
                params = ", ".join(
                    f"{self._java_type_to_string(p.java_type)} {p.name}"
                    for p in method.parameters
                )
                throws = " throws Exception" if method.exceptions else ""
                body = "".join(f"        {s}\n" for s in method_stmts)
                mods = " ".join(method.modifiers) if method.modifiers else "public static"
                ret = self._java_type_to_string(method.return_type) if method.return_type else "void"
                all_methods_src.append(
                    f"\n    {mods} {ret} {method.name}({params}){throws} {{\n{body}    }}\n"
                )

        extra_methods = "".join(all_methods_src)

        file_write_helper = ""
        file_write_imports = ""
        support_code = ""
        uses_cobol_file_io = uses_file_write or uses_cobol_file_io_stmt
        if uses_cobol_file_io:
            from engine.transformation.file_io_support_template import COBOL_FILE_IO_JAVA
            support_code = "\n" + COBOL_FILE_IO_JAVA + "\n"
        if uses_file_write:
            file_write_imports = (
                "import java.io.FileWriter;\n"
                "import java.io.PrintWriter;\n"
            )
            file_write_helper = (
                "\n"
                "    /** Append a text line to a file (sequential WRITE). */\n"
                "    static void _FileWriteHelper_appendLine(String path, String line) throws Exception {\n"
                "        try (PrintWriter _pw = new PrintWriter(new FileWriter(path, true))) {\n"
                "            _pw.println(line);\n"
                "        }\n"
                "    }\n"
            )
            # Rewrite _FileWriteHelper.appendLine calls to use the actual method name
            main_body = main_body.replace(
                "_FileWriteHelper.appendLine(", "_FileWriteHelper_appendLine("
            )
            extra_methods = extra_methods.replace(
                "_FileWriteHelper.appendLine(", "_FileWriteHelper_appendLine("
            )

        return f'''{file_write_imports}import java.io.PrintStream;

public class {class_name} {{
{declarations}
{extra_methods}
    public static void main(String[] args) throws Exception {{
        PrintStream out = System.out;
{main_body}    }}{file_write_helper}{support_code}}}
'''

    # ================================================================
    # IR-DRIVEN HELPER METHODS
    # ================================================================

    def _get_threshold_from_ir(self, threshold_rules: tuple[JavaThresholdRule, ...]) -> int:
        """Extract threshold from Java IR. No fallback — error if missing."""
        for tr in threshold_rules:
            return tr.value
        raise ValueError(
            "MISSING_REQUIRED_SEMANTIC: No threshold rule found. "
            "The generator cannot invent a business rule value."
        )

    def _generate_var_declarations_from_ir(
        self,
        status_codes: tuple[JavaStatusCodeMapping, ...],
        match_outcomes: tuple[JavaMatchOutcome, ...],
        summary_fields: tuple[JavaSummaryField, ...],
    ) -> str:
        """Generate Java variable declarations from Java IR metadata."""
        lines = []
        declared: set[str] = set()

        for sc in status_codes:
            if sc.counter_name not in declared:
                lines.append(f'        int {sc.counter_name} = 0;')
                declared.add(sc.counter_name)

        for mo in match_outcomes:
            for label in [mo.paid_label, mo.partial_label, mo.unpaid_label]:
                if label:
                    counter = self._label_to_counter_name(label)
                    if counter not in declared:
                        lines.append(f'        int {counter} = 0;')
                        declared.add(counter)

        for sf in summary_fields:
            if sf.java_var_name not in declared:
                lines.append(f'        int {sf.java_var_name} = 0;')
                declared.add(sf.java_var_name)

        return "\n".join(lines)

    def _generate_counter_increments_from_ir(
        self,
        summary_fields: tuple[JavaSummaryField, ...],
    ) -> str:
        """Generate counter increment statements for each loop iteration."""
        if summary_fields:
            first_var = summary_fields[0].java_var_name
            return f'            {first_var}++;'
        return ""

    def _generate_field_assignments_from_ir(
        self,
        program: JavaProgram,
        java_class: JavaClass,
    ) -> str:
        """Generate Java field assignment statements from input record fields."""
        # Build field lookup from class fields
        field_map = {f.name: f for f in java_class.fields}
        input_fields = program.input_record_fields or tuple(f.name for f in java_class.fields)

        lines = []
        for i, field_name in enumerate(input_fields):
            field = field_map.get(field_name)
            if field and field.java_type.basic_type and field.java_type.basic_type.value == "int":
                lines.append(f'            {field_name} = Integer.parseInt(rec[{i}].trim());')
            else:
                lines.append(f'            {field_name} = rec[{i}].trim();')
        return "\n".join(lines) if lines else ""

    def _derive_field_var(
        self,
        file_resource: JavaFileResource,
        java_class: JavaClass,
        index: int,
        default: str,
    ) -> str:
        """Derive a Java variable name from class fields by position."""
        if index < 0:
            index = len(java_class.fields) + index
        if 0 <= index < len(java_class.fields):
            return java_class.fields[index].name
        return default

    def _build_status_checks_java_from_ir(
        self,
        status_codes: tuple[JavaStatusCodeMapping, ...],
        match_outcomes: tuple[JavaMatchOutcome, ...],
        summary_fields: tuple[JavaSummaryField, ...],
        field_map: dict[str, JavaField],
        input_record_fields: tuple[str, ...] = (),
    ) -> str:
        """Generate Java if/else chain from Java IR status codes."""
        if not status_codes:
            return ""

        first_label = status_codes[0].label
        approval_label = status_codes[-1].label

        # Get match outcome labels
        paid_label = match_outcomes[0].paid_label if match_outcomes else approval_label
        partial_label = match_outcomes[0].partial_label if match_outcomes else approval_label
        unpaid_label = match_outcomes[0].unpaid_label if match_outcomes else first_label

        # Build label → counter mapping
        label_to_counter = {sc.label: sc.counter_name for sc in status_codes}
        for mo in match_outcomes:
            if mo.paid_label:
                label_to_counter[mo.paid_label] = self._label_to_counter_name(mo.paid_label)
            if mo.partial_label:
                label_to_counter[mo.partial_label] = self._label_to_counter_name(mo.partial_label)
            if mo.unpaid_label:
                label_to_counter[mo.unpaid_label] = self._label_to_counter_name(mo.unpaid_label)

        # Derive variable names from input record fields (positional)
        if input_record_fields:
            id_var = input_record_fields[0] if len(input_record_fields) > 0 else "field_0"
            status_var = input_record_fields[1] if len(input_record_fields) > 1 else "field_1"
            amt_str_var = input_record_fields[-1] if len(input_record_fields) > 0 else "field_last"
        else:
            id_var = self._derive_field_var_simple(field_map, 0, "field_0")
            status_var = self._derive_field_var_simple(field_map, 1, "field_1")
            amt_str_var = self._derive_field_var_simple(field_map, -1, "field_last")

        lines = []
        first = True
        for sc in status_codes:
            counter = label_to_counter.get(sc.label, sc.counter_name)
            keyword = "if" if first else "} else if"
            lines.append(f'            {keyword} ({status_var}.equals("{sc.code}")) {{')
            lines.append(f'                result = "{sc.label}";')
            lines.append(f'                {counter}++;')
            first = False

        lines.append('            } else {')
        lines.append(f'            if ({amt_str_var}_num < THRESHOLD) {{')
        lines.append(f'                result = "{first_label}";')
        lines.append(f'                {label_to_counter.get(first_label, "counter")}++;')
        lines.append('            } else {')
        lines.append(f'                result = "{approval_label}";')
        lines.append(f'                {label_to_counter.get(approval_label, "counter")}++;')

        # Lookup matching (if we have match outcomes)
        if match_outcomes and match_outcomes[0].paid_label:
            paid_counter = label_to_counter.get(paid_label, "paidCounter")
            partial_counter = label_to_counter.get(partial_label, "partialCounter")
            unpaid_counter = label_to_counter.get(unpaid_label, "unpaidCounter")
            lines.append('')
            lines.append(f'                if (lookupMap.containsKey({id_var}.trim())) {{')
            lines.append(f'                    lookupMatch = lookupMap.get({id_var}.trim());')
            lines.append('')
            lines.append(f'                    if (lookupMatch == {amt_str_var}_num) {{')
            lines.append(f'                        result = "{paid_label}";')
            lines.append(f'                        {paid_counter}++;')
            lines.append('                    } else {')
            lines.append(f'                        result = "{partial_label}";')
            lines.append(f'                        {partial_counter}++;')
            lines.append('                    }')
            lines.append('                } else {')
            lines.append(f'                    result = "{unpaid_label}";')
            lines.append(f'                    {unpaid_counter}++;')
            lines.append('                }')
        else:
            lines.append('                // Lookup not extracted from source')

        lines.append('            }')
        lines.append('            }')

        return "\n".join(lines)

    def _derive_field_var_simple(
        self,
        field_map: dict[str, JavaField],
        index: int,
        default: str,
    ) -> str:
        """Derive a Java variable name from field map by position."""
        fields = list(field_map.values())
        if index < 0:
            index = len(fields) + index
        if 0 <= index < len(fields):
            return fields[index].name
        return default

    def _build_summary_java_from_ir(
        self,
        summary_fields: tuple[JavaSummaryField, ...],
        field_map: dict[str, JavaField],
    ) -> str:
        """Build summary output lines from Java IR."""
        lines = []
        for sf in summary_fields:
            if sf.format_width > 0:
                lines.append(
                    f'        System.out.println("{sf.field_name}=" + '
                    f'String.format("%0{sf.format_width}d", {sf.java_var_name}));'
                )
            else:
                lines.append(
                    f'        System.out.println("{sf.field_name}=" + {sf.java_var_name});'
                )
        return "\n".join(lines)

    def _build_record_write_java_from_ir(
        self,
        writer_var: str,
        format_fields: tuple[str, ...],
        field_map: dict[str, JavaField],
    ) -> str:
        """Build Java printf/write statement from IR-derived record format."""
        if not format_fields:
            return f'            // Record format not extracted from source'

        fmt_parts = []
        args = []
        for name in format_fields:
            if (name.startswith('"') and name.endswith('"')) or \
               (name.startswith("'") and name.endswith("'")):
                literal = name[1:-1]
                fmt_parts.append("%s")
                args.append(f'"{literal}"')
            else:
                java_name = name.replace("-", "_")
                fmt_parts.append("%s")
                args.append(java_name)

        if not args:
            return f'            // No fields extracted'

        fmt_str = " ".join(fmt_parts)
        args_str = ",\n                        ".join(args)
        return f'            {writer_var}.printf("{fmt_str}%n",\n                        {args_str});'

    def _build_stderr_java_from_ir(
        self,
        status_codes: tuple[JavaStatusCodeMapping, ...],
        id_var: str,
        status_var: str,
        amt_str_var: str,
    ) -> str:
        """Build stderr diagnostic output from Java IR."""
        if not status_codes:
            return ""
        first_label = status_codes[0].label
        first_code = status_codes[0].code
        status_check = f'{status_var}.equals("{first_code}")'
        return f'''            if (result.equals("{first_label}")) {{
                System.err.printf("REJECT:%s reason=%s%n",
                        {id_var},
                        {status_var});
            }}
            if ({amt_str_var}_num < THRESHOLD && {status_check}) {{
                System.err.printf("LOW_VALUE:%s value=%s%n",
                        {id_var},
                        padRight(String.valueOf({amt_str_var}_num), 5));
            }}'''

    def _java_type_to_string(self, java_type) -> str:
        """Render a JavaType to its Java source string using the canonical renderer."""
        if java_type is None:
            return "void"
        try:
            return java_type.to_source()
        except Exception:
            return "void"

    @staticmethod
    def _escape_java_string(value: str) -> str:
        """Escape a raw string value for embedding in a Java string literal."""
        return value.replace("\\", "\\\\").replace('"', '\\"')

    def _gen_field_declarations_from_ir(self, java_class: JavaClass) -> str:
        """Generate Java variable declarations from JavaClass fields."""
        lines = []
        for field in java_class.fields:
            type_str = field.java_type.to_source()
            if field.initializer is not None:
                # Render through the literal renderer so String
                # initializers are always quoted (never bare identifiers).
                default = self._expr_to_string(field.initializer)
            elif type_str == "int":
                default = "0"
            elif type_str == "String":
                default = '""'
            else:
                default = "0"
            lines.append(f'    static {type_str} {field.name} = {default};')
        return "\n".join(lines)

    def _gen_parsing_java_from_ir(
        self,
        file_resource: JavaFileResource,
        java_class: JavaClass,
    ) -> str:
        """Generate Java parsing code from file resource and class fields."""
        lines = []
        for i, field in enumerate(java_class.fields):
            if field.java_type.basic_type and field.java_type.basic_type.value == "int":
                lines.append(f'            {field.name} = Integer.parseInt(rec[{i}].trim());')
            else:
                lines.append(f'            {field.name} = rec[{i}].trim();')
        return "\n".join(lines)

    def _stmt_to_string(self, stmt) -> str:
        """Convert a Java IR statement to a Java source string."""
        from engine.transformation.java_ir import (
            JavaAssignment, JavaMethodCallStatement, JavaReturn,
            JavaComment, JavaIf, JavaBlock, JavaFor, JavaWhile,
            JavaLocalVarDecl,
        )
        if isinstance(stmt, JavaAssignment):
            return f"{stmt.target} = {self._expr_to_string(stmt.expression)};"
        if isinstance(stmt, JavaLocalVarDecl):
            init_str = ""
            if stmt.initializer:
                init_str = f" = {self._expr_to_string(stmt.initializer)}"
            return f"{stmt.java_type.to_source()} {stmt.name}{init_str};"
        if isinstance(stmt, JavaMethodCallStatement):
            return self._method_call_to_string(stmt.call) + ";"
        if isinstance(stmt, JavaReturn):
            if stmt.expression:
                return f"return {self._expr_to_string(stmt.expression)};"
            return "return;"
        if isinstance(stmt, JavaComment):
            return f"// {stmt.text}"
        if isinstance(stmt, JavaIf):
            cond = self._expr_to_string(stmt.condition)
            # Strip outer parens from condition since if() already adds them
            if cond.startswith("(") and cond.endswith(")"):
                cond = cond[1:-1]
            lines = [f"if ({cond}) {{"]
            for s in stmt.then_body:
                lines.append(f"    {self._stmt_to_string(s)}")
            if stmt.else_body:
                lines.append("} else {")
                for s in stmt.else_body:
                    lines.append(f"    {self._stmt_to_string(s)}")
            lines.append("}")
            return "\n".join(lines)
        if isinstance(stmt, JavaFor):
            init_str = self._stmt_to_string(stmt.init).rstrip(";") if stmt.init else ""
            cond_str = self._expr_to_string(stmt.condition) if stmt.condition else ""
            update_str = self._stmt_to_string(stmt.update).rstrip(";") if stmt.update else ""
            lines = [f"for ({init_str}; {cond_str}; {update_str}) {{"]
            for s in stmt.body:
                inner = self._stmt_to_string(s)
                if inner:
                    for inner_line in inner.split("\n"):
                        lines.append(f"    {inner_line}")
            lines.append("}")
            return "\n".join(lines)
        if isinstance(stmt, JavaBlock):
            return "\n".join(self._stmt_to_string(s) for s in stmt.statements)
        if isinstance(stmt, JavaWhile):
            cond = self._expr_to_string(stmt.condition)
            lines = [f"while ({cond}) {{"]
            for s in stmt.body:
                inner = self._stmt_to_string(s)
                if inner:
                    for inner_line in inner.split("\n"):
                        lines.append(f"    {inner_line}")
            lines.append("}")
            return "\n".join(lines)
        return ""

    def _expr_to_string(self, expr) -> str:
        """Convert a Java IR expression to a Java source string."""
        from engine.transformation.java_ir import (
            JavaLiteral, JavaVariableRef, JavaBinaryOp, JavaMethodCall,
            JavaStringConcat, JavaUnaryOp,
        )
        if isinstance(expr, JavaLiteral):
            if expr.value == "null" and not expr.java_type:
                return "null"
            if expr.value in ("true", "false") and not expr.java_type:
                return expr.value
            # String literals need quotes; numeric literals don't
            # JavaLiteral without java_type may be a condition expression — don't quote
            if expr.java_type and expr.java_type.basic_type and \
               expr.java_type.basic_type.value == "String":
                return f'"{self._escape_java_string(expr.value)}"'
            # A single-quoted value is a COBOL string literal spelling, not a
            # Java char: normalize to a double-quoted Java string literal.
            if len(expr.value) >= 2 and expr.value.startswith("'") and expr.value.endswith("'"):
                return f'"{self._escape_java_string(expr.value[1:-1])}"'
            # If it looks like a string value (not a number, not a condition)
            if not expr.value.replace(".", "").replace("-", "").isdigit():
                # Check if it's a condition expression (contains operators)
                if any(op in expr.value for op in ("==", "!=", "<", ">", "<=", ">=", "&&", "||")):
                    return expr.value  # Don't quote conditions
                if not expr.value.startswith('"'):
                    return f'"{self._escape_java_string(expr.value)}"'
            return expr.value
        if isinstance(expr, JavaVariableRef):
            return expr.name
        if isinstance(expr, JavaBinaryOp):
            left = self._expr_to_string(expr.left)
            right = self._expr_to_string(expr.right)
            return f"({left} {expr.operator} {right})"
        if isinstance(expr, JavaUnaryOp):
            operand = self._expr_to_string(expr.operand)
            if any(op in operand for op in ("==", "!=", "&&", "||", ">=", "<=", "<", ">")):
                depth = 0
                grouped = False
                for i, ch in enumerate(operand):
                    if ch == "(":
                        depth += 1
                    elif ch == ")":
                        depth -= 1
                        if depth == 0:
                            grouped = i == len(operand) - 1
                            break
                if not grouped:
                    operand = f"({operand})"
            return f"({expr.operator}{operand})"
        if isinstance(expr, JavaMethodCall):
            return self._method_call_to_string(expr)
        if isinstance(expr, JavaStringConcat):
            parts = []
            for p in expr.parts:
                rendered = self._expr_to_string(p)
                # If it's a JavaLiteral with no type, wrap in quotes
                if isinstance(p, JavaLiteral) and not p.java_type:
                    if not rendered.startswith('"'):
                        rendered = f'"{rendered}"'
                parts.append(rendered)
            return " + ".join(parts)
        return ""

    def _method_call_to_string(self, call) -> str:
        """Convert a Java IR method call to a Java source string."""
        args = ", ".join(self._expr_to_string(a) for a in call.arguments)
        if call.is_static:
            return f"{call.class_name}.{call.method_name}({args})"
        if call.object_ref:
            return f"{self._expr_to_string(call.object_ref)}.{call.method_name}({args})"
        return f"{call.method_name}({args})"

    def _label_to_counter_name(self, label: str) -> str:
        """Convert a label string to a Java counter variable name."""
        parts = label.lower().split("_")
        return parts[0] + "".join(p.capitalize() for p in parts[1:])

    def _generate_decision_java(self, program: CobolProgram, class_name: str) -> str:
        """Generate Java with IR-derived decision logic.

        All values are derived from the top-level generic IR fields:
        - Status codes from program.status_codes
        - Threshold from program.threshold_rules
        - Record formats from program.output_formats
        - Lookup from program.lookup_operations

        Falls back to minimal generation if required structures are absent.
        """
        # If no status codes present, fall back to minimal generation.
        # caps.decision can be True from IF+MOVE patterns without status codes.
        if not program.status_codes:
            return self._generate_minimal_java(program, class_name)

        # Derive file roles from OPEN statements — not from path names
        input_files = self._get_files_by_role(program, "INPUT")
        output_files = self._get_files_by_role(program, "OUTPUT")

        if len(input_files) < 2 or len(output_files) < 2:
            raise ValueError(
                "MISSING_REQUIRED_SEMANTIC: Decision mode requires "
                "2 input files and 2 output files in FILE-CONTROL."
            )

        input1_path = input_files[0].container_path
        input2_path = input_files[1].container_path
        output1_path = output_files[0].container_path
        output2_path = output_files[1].container_path

        input1_filename = input1_path.rsplit("/", 1)[1] if "/" in input1_path else None
        input2_filename = input2_path.rsplit("/", 1)[1] if "/" in input2_path else None
        output1_filename = output1_path.rsplit("/", 1)[1] if "/" in output1_path else None
        output2_filename = output2_path.rsplit("/", 1)[1] if "/" in output2_path else None

        if not all([input1_filename, input2_filename, output1_filename, output2_filename]):
            raise ValueError(
                "MISSING_REQUIRED_SEMANTIC: File path must contain a filename. "
                "Cannot invent a filename from incomplete path metadata."
            )

        # IR-derived threshold — no fallback
        threshold = self._get_threshold_from_ir(program.threshold_rules)

        # IR-derived report header — no fallback
        if not program.report_header:
            raise ValueError(
                "MISSING_REQUIRED_SEMANTIC: No report header found in COBOL source."
            )
        report_header = program.report_header

        # IR-derived summary fields — no fallback
        if not program.summary_fields:
            raise ValueError(
                "MISSING_REQUIRED_SEMANTIC: No summary fields found in COBOL source."
            )
        summary_fields = program.summary_fields

        # IR-derived record formats from output_formats
        report_format = program.output_formats[0].record_format if len(program.output_formats) > 0 else None
        output_format = program.output_formats[1].record_format if len(program.output_formats) > 1 else None

        # Derive variable names from InputRecordMappings — positional, no name guessing
        # Primary record is the first InputRecordMapping (positional, not name-based)
        main_record = program.input_record_mappings[0] if program.input_record_mappings else None

        # Derive all field variables positionally from the record mapping
        field_vars = self._derive_field_vars(main_record) if main_record else {}

        # Build summary output lines — derive Java variable names generically
        summary_java = self._build_summary_java(summary_fields, program.working_storage)

        # Build status check Java code — derive field vars from record mapping
        # Use positional ordering: first field = ID, remaining fields by position
        id_var = field_vars.get(main_record.fields[0], "field_0") if main_record and main_record.fields else "field_0"
        status_var = field_vars.get(main_record.fields[1], "field_1") if main_record and len(main_record.fields) > 1 else "field_1"
        amt_str_var = field_vars.get(main_record.fields[-1], "field_last") if main_record and main_record.fields else "field_last"

        status_java = self._build_status_checks_java(
            program.status_codes, program.lookup_operations,
            program.match_outcome_labels, status_var, id_var, amt_str_var,
        )

        # Build record write Java
        cobol_to_java = self._derive_cobol_to_java_mapping(program)
        report_write = self._build_record_write_java(
            "rpt", report_format, cobol_to_java
        )
        output_write = self._build_record_write_java(
            "out", output_format, cobol_to_java
        )

        # Build stderr diagnostics
        stderr_java = self._build_stderr_java(program.status_codes, id_var, status_var, amt_str_var)

        # Generate variable declarations from summary fields
        var_decls = self._generate_var_declarations(
            program.status_codes, program.match_outcome_labels, summary_fields,
        )

        return f'''import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class {class_name} {{
    static final int THRESHOLD = {threshold};

    public static void main(String[] args) throws Exception {{
        String inputDir = args.length > 0 ? args[0] : "{input1_path.rsplit('/', 1)[0]}";
        String outputDir = args.length > 1 ? args[1] : "{output1_path.rsplit('/', 1)[0]}";

{var_decls}

        List<String[]> input1 = readInput(inputDir + "/{input1_filename}");
        List<String[]> input2 = readInput(inputDir + "/{input2_filename}");

        Map<String, Integer> lookupMap = new LinkedHashMap<>();
        for (String[] r : input2) {{
            String key = r[1].trim();
            int value = Integer.parseInt(r[3].trim());
            lookupMap.put(key, value);
        }}

        PrintWriter rpt = new PrintWriter(new FileWriter(outputDir + "/{output1_filename}"));
        PrintWriter out = new PrintWriter(new FileWriter(outputDir + "/{output2_filename}"));

        rpt.println("{report_header}");
        rpt.println();

        for (String[] rec : input1) {{
{self._generate_counter_increments(program.status_codes, summary_fields)}
{self._generate_field_assignments(main_record, field_vars)}

            int {amt_str_var}_num = Integer.parseInt({amt_str_var}.trim());

            String result;
            int lookupMatch = 0;

{status_java}

{report_write}

{output_write}

{stderr_java}
        }}

{summary_java}

        rpt.close();
        out.close();
    }}

    static List<String[]> readInput(String path) throws Exception {{
        List<String[]> rows = new ArrayList<>();
        BufferedReader br = new BufferedReader(new FileReader(path));
        String line;
        while ((line = br.readLine()) != null) {{
            if (!line.trim().isEmpty()) {{
                rows.add(line.split("\\\\|", -1));
            }}
        }}
        br.close();
        return rows;
    }}

    static String padRight(String s, int n) {{
        if (s == null) {{
            s = "";
        }}
        if (s.length() >= n) {{
            return s.substring(0, n);
        }}
        StringBuilder sb = new StringBuilder(s);
        while (sb.length() < n) {{
            sb.append(' ');
        }}
        return sb.toString();
    }}
}}
'''

    def _generate_var_declarations(
        self,
        status_codes: tuple,
        match_labels: tuple[str, ...],
        summary_fields: tuple[str, ...],
    ) -> str:
        """Generate Java variable declarations from status codes, match labels, and summary fields.

        Counter variables are derived from status code labels and match outcome labels.
        Summary variables are derived from COBOL field names.
        """
        lines = []
        # Declare counter variables from status codes
        declared: set[str] = set()
        for sc in status_codes:
            counter_name = self._label_to_counter_name(sc.label)
            lines.append(f'        int {counter_name} = 0;')
            declared.add(counter_name)
        # Declare counter variables from match outcome labels
        for label in match_labels:
            counter_name = self._label_to_counter_name(label)
            if counter_name not in declared:
                lines.append(f'        int {counter_name} = 0;')
                declared.add(counter_name)
        # Declare summary variables from COBOL field names
        for field in summary_fields:
            java_var = self._cobol_field_to_java_var(field)
            if java_var not in declared:
                lines.append(f'        int {java_var} = 0;')
                declared.add(java_var)
        return "\n".join(lines)

    def _generate_counter_increments(self, status_codes: tuple, summary_fields: tuple[str, ...]) -> str:
        """Generate counter increment statements for each loop iteration."""
        lines = []
        # Increment "totalCount" or first summary field
        if summary_fields:
            first_var = self._cobol_field_to_java_var(summary_fields[0])
            lines.append(f'            {first_var}++;')
        return "\n".join(lines)

    def _label_to_counter_name(self, label: str) -> str:
        """Convert a label string to a Java counter variable name.

        Uses the same derivation as _cobol_field_to_java_var.
        Example: "REJECTED" → "rejected"
        """
        return self._cobol_field_to_java_var(label)

    def _derive_cobol_to_java_mapping(self, program: CobolProgram) -> dict[str, str]:
        """Derive COBOL→Java variable name mapping from InputRecordMappings.

        Uses the first InputRecordMapping to map COBOL field names to
        Java variable names derived from the field names.
        """
        mapping: dict[str, str] = {}
        if program.input_record_mappings:
            for field in program.input_record_mappings[0].fields:
                java_name = field.replace("-", "_")
                mapping[field] = java_name
        return mapping

    def _find_field_var(self, mapping: InputRecordMapping | None, *hints: str) -> str:
        """Find a Java variable name from InputRecordMapping matching any of the hints."""
        if not mapping:
            return "field_" + "_".join(hints)
        for field in mapping.fields:
            field_lower = field.lower()
            if any(h in field_lower for h in hints):
                return field.replace("-", "_")
        return "field_" + "_".join(hints)

    def _derive_field_vars(self, mapping: InputRecordMapping) -> dict[str, str]:
        """Derive Java variable names from InputRecordMapping fields positionally.

        Each COBOL field name maps to a Java variable name derived from the field.
        No domain-specific name guessing — uses actual field names from COBOL source.
        """
        result: dict[str, str] = {}
        for field in mapping.fields:
            java_name = field.replace("-", "_")
            result[field] = java_name
        return result

    def _generate_field_assignments(self, mapping: InputRecordMapping | None,
                                     field_vars: dict[str, str]) -> str:
        """Generate Java field assignment statements from InputRecordMapping."""
        if not mapping:
            return ""
        lines = []
        for i, field in enumerate(mapping.fields):
            java_name = field_vars.get(field, field.replace("-", "_"))
            lines.append(f'            String {java_name} = rec[{i}];')
        return "\n".join(lines)

    def _get_threshold_from_ir(self, threshold_rules: tuple) -> int:
        """Extract threshold from IR. No fallback — error if missing."""
        for tr in threshold_rules:
            return tr.value
        raise ValueError(
            "MISSING_REQUIRED_SEMANTIC: No threshold rule found in COBOL source. "
            "The generator cannot invent a business rule value."
        )

    def _get_files_by_role(self, program: CobolProgram, role: str) -> list:
        """Get file definitions by OPEN role (INPUT/OUTPUT/I-O/EXTEND).

        Derives file roles from OPEN statements — not from path names.
        Falls back to file_definitions ordering if no OPEN statements exist.
        """
        open_files = set()
        for stmt in program.open_statements:
            if stmt.mode.upper() == role:
                open_files.add(stmt.file_name)

        if open_files:
            return [fd for fd in program.file_definitions if fd.name in open_files]

        # Fallback: use file_definitions ordering (positional)
        return list(program.file_definitions)

    def _build_status_checks_java(
        self,
        status_codes: tuple,
        lookup_operations: tuple,
        match_outcome_labels: tuple[str, ...],
        status_var: str = "status",
        id_var: str = "field_0",
        amt_str_var: str = "field_3",
    ) -> str:
        """Generate Java if/else chain from IR status codes and threshold.

        Labels and counters are derived from status_codes.
        Counter variable names are derived from COBOL summary field names.
        Match outcome labels are derived from match_outcome_labels.
        """
        status_checks = [(sc.code, sc.label) for sc in status_codes]
        if not status_checks:
            return ""

        first_label = status_checks[0][1]
        approval_label = status_checks[-1][1]

        # Get match outcome labels from IR
        match_labels = list(match_outcome_labels)
        paid_label = match_labels[0] if len(match_labels) > 0 else approval_label
        partial_label = match_labels[1] if len(match_labels) > 1 else approval_label
        unpaid_label = match_labels[2] if len(match_labels) > 2 else first_label

        # Map labels to counter variable names using COBOL field name convention
        label_to_counter = {}
        for code, label in status_checks:
            label_to_counter[label] = self._cobol_field_to_java_var(label)
        # Also map match outcome labels to counters
        for label in match_labels:
            if label not in label_to_counter:
                label_to_counter[label] = self._cobol_field_to_java_var(label)

        lines = []
        first = True
        for code, label in status_checks:
            counter = label_to_counter[label]
            keyword = "if" if first else "} else if"
            lines.append(f'            {keyword} ({status_var}.equals("{code}")) {{')
            lines.append(f'                result = "{label}";')
            lines.append(f'                {counter}++;')
            first = False

        lines.append('            } else {')
        lines.append(f'            if ({amt_str_var}_num < THRESHOLD) {{')
        lines.append(f'                result = "{first_label}";')
        lines.append(f'                {label_to_counter[first_label]}++;')
        lines.append('            } else {')
        lines.append(f'                result = "{approval_label}";')
        lines.append(f'                {label_to_counter[approval_label]}++;')

        # IR-derived table lookup matching
        if lookup_operations:
            lines.append('')
            lines.append(f'                if (lookupMap.containsKey({id_var}.trim())) {{')
            lines.append(f'                    lookupMatch = lookupMap.get({id_var}.trim());')
            lines.append('')
            lines.append(f'                    if (lookupMatch == {amt_str_var}_num) {{')
            lines.append(f'                        result = "{paid_label}";')
            lines.append(f'                        {label_to_counter[paid_label]}++;')
            lines.append('                    } else {')
            lines.append(f'                        result = "{partial_label}";')
            lines.append(f'                        {label_to_counter[partial_label]}++;')
            lines.append('                    }')
            lines.append('                } else {')
            lines.append(f'                    result = "{unpaid_label}";')
            lines.append(f'                    {label_to_counter[unpaid_label]}++;')
            lines.append('                }')
        else:
            lines.append('                // Lookup not extracted from COBOL source')

        lines.append('            }')
        lines.append('            }')

        return "\n".join(lines)

    def _build_summary_java(self, summary_fields: tuple[str, ...],
                            working_storage: tuple = ()) -> str:
        """Build summary output lines from IR-derived field names.

        Java variable names are derived generically from COBOL field names.
        Format width is derived from PIC metadata — not from field names.
        """
        # Build lookup: field name → DataItem from working_storage
        ws_lookup: dict[str, object] = {}
        for item in working_storage:
            ws_lookup[item.name] = item

        lines = []
        for field in summary_fields:
            java_var = self._cobol_field_to_java_var(field)
            data_item = ws_lookup.get(field)
            if data_item and hasattr(data_item, "format_width"):
                width = data_item.format_width
                if width < 1:
                    width = 1
                lines.append(
                    f'        System.out.println("{field}=" + String.format("%0{width}d", {java_var}));'
                )
            else:
                lines.append(
                    f'        System.out.println("{field}=" + {java_var});'
                )
        return "\n".join(lines)

    def _build_record_write_java(
        self, writer_var: str, fmt: RecordFormat | None,
        cobol_to_java: dict[str, str],
    ) -> str:
        """Build Java printf/write statement from IR-derived record format.

        The RecordFormat.fields alternates between COBOL field names and
        literal delimiter values (e.g. " " or "|"). Fields that start
        with a quote are literal values; others are COBOL variable references
        that are mapped to Java local variables via cobol_to_java.
        """
        if not fmt or not fmt.fields:
            return '            // Record format not extracted from COBOL source'

        fmt_parts = []  # printf format specifiers
        args = []  # printf arguments

        for fd in fmt.fields:
            name = fd.field_name
            if name.startswith('"') and name.endswith('"'):
                # Literal value (e.g. " " or "|")
                literal = name[1:-1]
                fmt_parts.append("%s")
                args.append(f'"{literal}"')
            elif name.startswith("'") and name.endswith("'"):
                # Single-quoted literal
                literal = name[1:-1]
                fmt_parts.append("%s")
                args.append(f'"{literal}"')
            else:
                # COBOL field reference → Java local variable
                java_name = cobol_to_java.get(name, name.replace("-", "_"))
                fmt_parts.append("%s")
                args.append(java_name)

        if not args:
            return f'            // No fields extracted for {fmt.record_name}'

        fmt_str = " ".join(fmt_parts)
        args_str = ",\n                        ".join(args)
        return f'            {writer_var}.printf("{fmt_str}%n",\n                        {args_str});'

    def _build_table_lookup_java(self, pl: LookupOperation) -> str:
        """Build table lookup Java from IR-derived LookupOperation."""
        return ""

    def _build_stderr_java(self, status_codes: tuple, id_var: str = "field_0",
                           status_var: str = "status",
                           amt_str_var: str = "field_3") -> str:
        """Build stderr diagnostic output from IR-derived status codes."""
        if not status_codes:
            return ""
        first_label = status_codes[0].label
        first_code = status_codes[0].code
        status_check = f'{status_var}.equals("{first_code}")'
        return f'''            if (result.equals("{first_label}")) {{
                System.err.printf("REJECT:%s reason=%s%n",
                        {id_var},
                        {status_var});
            }}
            if ({amt_str_var}_num < THRESHOLD && {status_check}) {{
                System.err.printf("LOW_VALUE:%s value=%s%n",
                        {id_var},
                        padRight(String.valueOf({amt_str_var}_num), 5));
            }}'''

    def _generate_file_io_java(self, program: CobolProgram, class_name: str) -> str:
        """Generate Java for a COBOL program with file I/O via UNSTRING.

        Uses InputRecordMappings to derive variable declarations, parsing code,
        and field assignments. No workload-specific logic.
        """
        mappings = program.input_record_mappings
        input_files = self._get_files_by_role(program, "INPUT")

        if not input_files:
            raise ValueError(
                "MISSING_REQUIRED_SEMANTIC: No input files found in FILE-CONTROL."
            )

        input_path = input_files[0].container_path
        input_dir = input_path.rsplit("/", 1)[0] if "/" in input_path else "."
        input_filename = input_path.rsplit("/", 1)[1] if "/" in input_path else None

        if not input_filename:
            raise ValueError(
                "MISSING_REQUIRED_SEMANTIC: Input file path must contain a filename. "
                "Cannot invent a filename from incomplete path metadata."
            )

        # Derive variable declarations from InputRecordMappings + WORKING-STORAGE
        declarations = self._gen_io_variable_declarations(program, mappings)

        # Derive parsing code from first InputRecordMapping
        parsing = self._gen_unstring_parsing_java(mappings[0], program) if mappings else ""

        # Separate main paragraph from loop body paragraphs
        main_stmts = []
        loop_stmts = []
        for para in program.paragraphs:
            for stmt in para.statements:
                if isinstance(stmt, PerformStatement):
                    # The PERFORM target is the loop body
                    for inner_para in program.paragraphs:
                        if inner_para.name == stmt.paragraph_name:
                            for inner_stmt in inner_para.statements:
                                loop_stmts.extend(
                                    self._extract_statements(inner_stmt)
                                )
                else:
                    main_stmts.append(stmt)

        main_body = "\n".join(
            g for s in main_stmts if (g := self._gen_statement(s))
        )
        loop_body = "\n".join(
            g for s in loop_stmts if (g := self._gen_statement(s))
        )

        return f'''import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

public class {class_name} {{

{declarations}

    public static void main(String[] args) throws Exception {{
        String inputDir = args.length > 0 ? args[0] : "{input_dir}";
        PrintStream out = System.out;

        List<String[]> records = new ArrayList<>();
        BufferedReader br = new BufferedReader(new FileReader(inputDir + "/{input_filename}"));
        String line;
        while ((line = br.readLine()) != null) {{
            if (!line.trim().isEmpty()) {{
                records.add(line.split("\\\\|", -1));
            }}
        }}
        br.close();

        for (String[] rec : records) {{
{parsing}

{loop_body}
        }}

{main_body}
    }}
}}
'''

    def _gen_io_variable_declarations(
        self,
        program: CobolProgram,
        mappings: tuple[InputRecordMapping, ...],
    ) -> str:
        """Generate Java variable declarations from InputRecordMappings and WORKING-STORAGE.

        Uses PIC types from WORKING-STORAGE to determine int vs String.
        """
        lines = []
        # Build lookup: field name → DataItem from WORKING-STORAGE
        ws_lookup: dict[str, object] = {}
        for item in program.working_storage:
            ws_lookup[item.name] = item

        # Declare variables from first InputRecordMapping (main input)
        if mappings:
            seen: set[str] = set()
            for field in mappings[0].fields:
                java_name = field.replace("-", "_")
                if java_name not in seen:
                    seen.add(java_name)
                    # Check WORKING-STORAGE for type
                    ws_item = ws_lookup.get(field)
                    if ws_item and ws_item.is_numeric:
                        default = "0"
                        if ws_item.value:
                            default = ws_item.value.strip("'\"")
                        lines.append(f'    static int {java_name} = {default};')
                    else:
                        lines.append(f'    static String {java_name} = "";')
        # Also declare any additional WORKING-STORAGE items not already declared
        declared = {m.replace("-", "_") for m in mappings[0].fields} if mappings else set()
        for item in program.working_storage:
            java_name = item.name.replace("-", "_")
            if java_name not in declared:
                if item.is_numeric:
                    default = "0"
                    if item.value:
                        default = item.value.strip("'\"")
                    lines.append(f'    static int {java_name} = {default};')
                else:
                    default = '""'
                    if item.value:
                        default = f'"{item.value.strip("'\"")}"'
                    lines.append(f'    static String {java_name} = {default};')
        return "\n".join(lines)

    def _gen_unstring_parsing_java(self, mapping: InputRecordMapping, program: CobolProgram) -> str:
        """Generate Java parsing code from an InputRecordMapping.

        Generates: field = rec[index].trim(); for String fields,
                   field = Integer.parseInt(rec[index].trim()); for int fields.
        """
        ws_lookup: dict[str, object] = {}
        for item in program.working_storage:
            ws_lookup[item.name] = item

        lines = []
        for i, field in enumerate(mapping.fields):
            java_name = field.replace("-", "_")
            ws_item = ws_lookup.get(field)
            if ws_item and ws_item.is_numeric:
                lines.append(f'            {java_name} = Integer.parseInt(rec[{i}].trim());')
            else:
                lines.append(f'            {java_name} = rec[{i}].trim();')
        return "\n".join(lines)

    def _extract_statements(self, stmt: Statement) -> list[Statement]:
        """Recursively extract flat list of statements from compound statements.

        ReadStatement contains at_end_body and not_at_end_body which hold
        the actual processing statements. This method flattens them.
        IfStatement is kept as-is (the generator handles its internal structure).
        """
        if isinstance(stmt, ReadStatement):
            result = []
            for s in stmt.not_at_end_body:
                result.extend(self._extract_statements(s))
            for s in stmt.at_end_body:
                result.extend(self._extract_statements(s))
            return result
        return [stmt]

    def _generate_minimal_java(self, program: CobolProgram, class_name: str) -> str:
        """Generate Java for a minimal COBOL program.

        Supports: MOVE, ADD, IF/ELSE, DISPLAY, STOP RUN.
        """
        declarations = self._gen_variable_declarations(program)
        main_body = self._gen_paragraph_statements(program)

        return f'''import java.io.PrintStream;

public class {class_name} {{
{declarations}

    public static void main(String[] args) throws Exception {{
        PrintStream out = System.out;
{main_body}
    }}
}}
'''

    def _gen_variable_declarations(self, program: CobolProgram) -> str:
        """Generate Java variable declarations from WORKING-STORAGE."""
        lines = []
        for item in program.working_storage:
            java_name = item.name.replace("-", "_")
            if item.is_numeric:
                default = "0"
                if item.value:
                    default = item.value.strip("'\"")
                lines.append(f'    static int {java_name} = {default};')
            else:
                default = '""'
                if item.value:
                    default = f'"{item.value.strip("'\"")}"'
                lines.append(f'    static String {java_name} = {default};')
        return "\n".join(lines)

    def _gen_paragraph_statements(self, program: CobolProgram) -> str:
        """Generate Java statements from paragraphs."""
        lines = []
        for para in program.paragraphs:
            for stmt in para.statements:
                generated = self._gen_statement(stmt)
                if generated:
                    lines.append(generated)
        return "\n".join(lines)

    def _gen_statement(self, stmt: Statement) -> str | None:
        """Generate Java code for a single COBOL statement."""
        if isinstance(stmt, MoveStatement):
            target = stmt.target.replace("-", "_")
            source = self._cobol_expr_to_java(stmt.source)
            return f"        {target} = {source};"

        if isinstance(stmt, AddStatement):
            # ADD A TO B GIVING C → C = A + B  (C receives result, B unchanged)
            # ADD A TO B           → B = A + B  (in-place)
            target = stmt.giving_target.replace("-", "_") if stmt.giving_target else stmt.target.replace("-", "_")
            source_a = self._cobol_expr_to_java(stmt.source)
            source_b = stmt.target.replace("-", "_")
            if stmt.giving_target:
                return f"        {target} = ({source_a} + {source_b});"
            else:
                return f"        {target} = ({source_b} + {source_a});"

        if isinstance(stmt, DivideStatement):
            target = stmt.target.replace("-", "_")
            source = self._cobol_expr_to_java(stmt.source)
            divisor = self._cobol_expr_to_java(stmt.divisor)
            return f"        {target} = {source} / {divisor};"

        if isinstance(stmt, DisplayStatement):
            parts = []
            for part in stmt.parts:
                if part.startswith('"'):
                    inner = part[1:-1]
                    if inner:
                        parts.append(inner)
                else:
                    java_name = part.replace("-", "_")
                    parts.append(f'" + {java_name} + "')
            if not parts:
                return None
            content = "".join(parts)
            dest = "out" if stmt.destination != "STDERR" else "System.err"
            return f'        {dest}.println("{content}");'

        if isinstance(stmt, IfStatement):
            java_cond = self._cobol_condition_to_java(stmt.condition)
            lines = [f"        if ({java_cond}) {{"]
            for s in stmt.then_body:
                g = self._gen_statement(s)
                if g:
                    lines.append(g)
            if stmt.else_body:
                lines.append("        } else {")
                for s in stmt.else_body:
                    g = self._gen_statement(s)
                    if g:
                        lines.append(g)
            lines.append("        }")
            return "\n".join(lines)

        if isinstance(stmt, GoToStatement):
            return f"        // GO TO {stmt.target} (not implemented)"

        if isinstance(stmt, StopRunStatement):
            return None

        return None

    def _cobol_field_to_java_var(self, field_name: str) -> str:
        """Convert a COBOL summary field name to the Java local variable name.

        Converts SUMMARY_LABEL -> summaryLabel (camelCase).
        """
        parts = field_name.lower().split("_")
        return parts[0] + "".join(p.capitalize() for p in parts[1:])

    def _cobol_expr_to_java(self, expr: str) -> str:
        """Convert a COBOL expression to Java."""
        expr = expr.strip().rstrip(".")
        if expr.isdigit():
            return expr
        if (expr.startswith("'") and expr.endswith("'")) or \
           (expr.startswith('"') and expr.endswith('"')):
            inner = expr[1:-1]
            return f'"{inner}"'
        return expr.replace("-", "_")

    def _cobol_condition_to_java(self, condition: str) -> str:
        """Convert a COBOL condition to Java."""
        condition = condition.strip().rstrip(".")
        condition = re.sub(r'\bAND\b', '&&', condition, flags=re.IGNORECASE)
        condition = re.sub(r'\bOR\b', '||', condition, flags=re.IGNORECASE)
        condition = re.sub(r'\bNOT\b', '!', condition, flags=re.IGNORECASE)
        condition = condition.replace("-", "_")
        return condition
