"""Producer manifest — metadata about the transformation process.

The manifest is metadata. It is NOT equivalence evidence.
The validation engine determines equivalence independently.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass(frozen=True)
class ProducerManifest:
    """Metadata about a transformation run.

    This manifest is generated by the producer. It is NOT authoritative
    certification. The validation engine independently determines equivalence.
    """
    producer_identity: str
    producer_version: str
    success: bool
    source_hash: str
    source_path: str = ""
    program_id: str = ""
    generated_files: dict[str, str] = field(default_factory=dict)  # filename → hash
    entrypoint: str = ""
    java_version: str = "17"
    supported_scope: str = ""
    transformation_timestamp: str = ""
    runtime_requirements: tuple[str, ...] = ()
    diagnostics: tuple[str, ...] = ()
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def create(
        cls,
        producer_identity: str,
        producer_version: str,
        cobol_source: str,
        source_path: str = "",
        program_id: str = "",
        generated_files: dict[str, str] | None = None,
        entrypoint: str = "",
        supported_scope: str = "",
        runtime_requirements: tuple[str, ...] = (),
        diagnostics: tuple[str, ...] = (),
        metadata: dict[str, Any] | None = None,
    ) -> ProducerManifest:
        """Create a producer manifest."""
        source_hash = hashlib.sha256(cobol_source.encode("utf-8")).hexdigest()

        file_hashes = {}
        if generated_files:
            for filename, source in generated_files.items():
                file_hash = hashlib.sha256(source.encode("utf-8")).hexdigest()
                file_hashes[filename] = f"sha256:{file_hash}"

        return cls(
            producer_identity=producer_identity,
            producer_version=producer_version,
            success=True,
            source_hash=f"sha256:{source_hash}",
            source_path=source_path,
            program_id=program_id,
            generated_files=file_hashes,
            entrypoint=entrypoint,
            supported_scope=supported_scope,
            transformation_timestamp=datetime.now(timezone.utc).isoformat(),
            runtime_requirements=runtime_requirements,
            diagnostics=diagnostics,
            metadata=metadata or {},
        )

    @classmethod
    def create_failure(
        cls,
        producer_identity: str,
        producer_version: str,
        cobol_source: str,
        errors: tuple[str, ...] = (),
    ) -> ProducerManifest:
        """Create a manifest for a failed transformation."""
        source_hash = hashlib.sha256(cobol_source.encode("utf-8")).hexdigest()

        return cls(
            producer_identity=producer_identity,
            producer_version=producer_version,
            success=False,
            source_hash=f"sha256:{source_hash}",
            transformation_timestamp=datetime.now(timezone.utc).isoformat(),
            diagnostics=errors,
        )
